import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faChevronRight,
  faChevronDown,
  faTrash,
  faSpinner,
  faPlus,
  faSave,
  faPencilAlt,
  faFileAlt,
  faInfoCircle
} from '@fortawesome/free-solid-svg-icons';
import { motion, AnimatePresence } from 'framer-motion';
import toast, { Toaster } from 'react-hot-toast';
import Stepper from '../components/Stepper';
import MeasurementTable from './MeasurementTable';

// ✅ API BASE
const API_BASE_URL = "http://24.101.103.87:8082/api";
const jwtToken =  "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5MjA5MTYwNjEyIiwiaWF0IjoxNzQ0MjAyNDEzLCJleHAiOjE3NDQyODg4MTN9.cxCaFHJsjjmwxjCOSHwov6xVsxaZsn9AWTDqnSwhXK0";

const EditSubEstimateForm = () => {
  const [workOrderInfo, setWorkOrderInfo] = useState({});
  const [subworks, setSubworks] = useState([]);
  const [items, setItems] = useState({});
  const [visibleMeasurements, setVisibleMeasurements] = useState({});
  const [expandedSubworks, setExpandedSubworks] = useState([]);
  const [itemOptions, setItemOptions] = useState([]);
  const [showAddItemModal, setShowAddItemModal] = useState(false);
  const [itemFormErrors, setItemFormErrors] = useState({});
  const [editingItemId, setEditingItemId] = useState(null);
  const [itemForm, setItemForm] = useState({
    id: 0, srNo: 0, itemNo: '', category: '', descriptionOfItem: '',
    floorLiftRise: 'Ground floor', fkSubworkId: 0, fkWorkorderId: 0,
    completedRate: 0, labourRate: 0, scadaFlag: false, smallUnit: '',
    fullUnit: '', additionalSpecification: ''
  });

  const navigate = useNavigate();

  useEffect(() => {
    const wInfo = {
      workOrderId: localStorage.getItem('workorderId'),
      reviseId: localStorage.getItem('reviseId'),
      nameOfWork: localStorage.getItem('nameOfWork'),
      autogenerated: localStorage.getItem('autogenerated'),
      reviseno: localStorage.getItem('reviseno'),
    };
    setWorkOrderInfo(wInfo);
    fetchSubworks(wInfo.reviseId, wInfo.workOrderId);
    fetchItemOptions();
  }, []);

  const fetchSubworks = async (reviseId, workOrderId) => {
    try {
      const res = await fetch(`${API_BASE_URL}/subwork/${reviseId}/${workOrderId}`, {
        headers: { Authorization: `Bearer ${jwtToken}` }
      });
      const data = await res.json();
      setSubworks(data);
    } catch (err) {
      console.error(err);
    }
  };

  const fetchItemOptions = async () => {
    const res = await fetch(`${API_BASE_URL}/txn-items`, {
      headers: { Authorization: `Bearer ${jwtToken}` }
    });
    const data = await res.json();
    setItemOptions([...new Map(data.map(i => [i.itemNo, i])).values()]);
  };

  const toggleSubwork = (subworkId) => {
    setExpandedSubworks(prev =>
      prev.includes(subworkId) ? prev.filter(id => id !== subworkId) : [...prev, subworkId]
    );
    if (!items[subworkId]) loadSubworkItems(subworkId);
  };

  const loadSubworkItems = async (subworkId) => {
    const res = await fetch(`${API_BASE_URL}/txn-items`, {
      headers: { Authorization: `Bearer ${jwtToken}` }
    });
    const all = await res.json();
    const filtered = all.filter(i => i.fkSubworkId === subworkId);
    setItems(prev => ({ ...prev, [subworkId]: filtered }));
  };

  const addItemToSubwork = (subworkId) => {
    setItemForm({ ...itemForm, fkSubworkId: subworkId, fkWorkorderId: parseInt(workOrderInfo.workOrderId) });
    setEditingItemId(null);
    setShowAddItemModal(true);
  };

  const handleItemChange = (e) => {
    const itemNo = e.target.value;
    const found = itemOptions.find(i => i.itemNo === itemNo);
    if (found) {
      setItemForm({
        ...itemForm,
        ...found,
        itemNo: found.itemNo,
        fkSubworkId: itemForm.fkSubworkId,
        fkWorkorderId: itemForm.fkWorkorderId
      });
    }
  };

  const saveItem = async () => {
    const method = editingItemId ? 'PUT' : 'POST';
    const url = editingItemId ? `${API_BASE_URL}/txn-items/${editingItemId}` : `${API_BASE_URL}/txn-items`;
    const res = await fetch(url, {
      method,
      headers: {
        Authorization: `Bearer ${jwtToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(itemForm)
    });
    await loadSubworkItems(itemForm.fkSubworkId);
    setShowAddItemModal(false);
  };

  const editItem = (item) => {
    setItemForm({ ...item });
    setEditingItemId(item.id);
    setShowAddItemModal(true);
  };

  const deleteItem = async (itemId, subworkId) => {
    await fetch(`${API_BASE_URL}/txn-items/${itemId}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${jwtToken}` }
    });
    loadSubworkItems(subworkId);
  };

  return (
    <div className="p-6 bg-white">
      <Toaster />
      <Stepper currentStep={2} />

      {subworks.map(subwork => (
        <div key={subwork.id} className="mt-6 border border-gray-200 rounded-lg">
          <div className="flex justify-between items-center p-4 bg-gray-100">
            <h3 className="text-lg font-semibold">{subwork.subworkName}</h3>
            <button onClick={() => addItemToSubwork(subwork.id)} className="bg-blue-600 text-white px-3 py-1 rounded">
              <FontAwesomeIcon icon={faPlus} className="mr-1" /> Add Item
            </button>
          </div>

          {(items[subwork.id] || []).map((item, index) => (
            <div key={item.id} className="border-t px-4 py-2">
              <div className="flex justify-between items-center">
                <div>
                  <div className="font-semibold">{item.itemNo} - {item.category}</div>
                  <div className="text-gray-600">{item.descriptionOfItem}</div>
                </div>
                <div className="space-x-2">
                  <button onClick={() => editItem(item)} className="text-blue-600"><FontAwesomeIcon icon={faPencilAlt} /></button>
                  <button onClick={() => deleteItem(item.id, subwork.id)} className="text-red-600"><FontAwesomeIcon icon={faTrash} /></button>
                </div>
              </div>
              <MeasurementTable itemId={item.id} token={jwtToken} unitLabel={item.smallUnit} />
            </div>
          ))}
        </div>
      ))}

      {showAddItemModal && (
        <div className="fixed inset-0 bg-black bg-opacity-30 flex items-center justify-center z-50">
          <div className="bg-white rounded-lg p-6 w-full max-w-3xl">
            <h3 className="text-lg font-semibold mb-4">{editingItemId ? 'Edit Item' : 'Add Item'}</h3>
            <select name="itemNo" value={itemForm.itemNo} onChange={handleItemChange} className="w-full mb-4 p-2 border rounded">
              <option value="">Select Item</option>
              {itemOptions.map((opt, i) => (
                <option key={i} value={opt.itemNo}>{opt.itemNo}</option>
              ))}
            </select>
            <div className="grid grid-cols-2 gap-4">
              <input value={itemForm.category} onChange={e => setItemForm({ ...itemForm, category: e.target.value })} className="p-2 border rounded" placeholder="Category" />
              <input value={itemForm.floorLiftRise} onChange={e => setItemForm({ ...itemForm, floorLiftRise: e.target.value })} className="p-2 border rounded" placeholder="Floor Lift Rise" />
              <textarea value={itemForm.descriptionOfItem} onChange={e => setItemForm({ ...itemForm, descriptionOfItem: e.target.value })} className="col-span-2 p-2 border rounded" placeholder="Description" />
            </div>
            <div className="mt-4 flex justify-end gap-3">
              <button onClick={() => setShowAddItemModal(false)} className="bg-gray-300 px-4 py-2 rounded">Cancel</button>
              <button onClick={saveItem} className="bg-blue-600 text-white px-4 py-2 rounded">{editingItemId ? 'Update' : 'Save'}</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default EditSubEstimateForm;