import React, { useEffect, useState } from 'react';
import Stepper from '../components/Stepper';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { FileText, Check, Download, ChevronDown, X, Eye, FileCheck } from 'lucide-react';
import { 
  Document, 
  Page, 
  Text, 
  View, 
  StyleSheet, 
  PDFDownloadLink, 
  Font,
  pdf 
} from '@react-pdf/renderer';
import { MeasurementPDF } from './PDFComponent/MeasurementPDF';
import { AbstractPDF } from './PDFComponent/AbstractPDF';
import { CoverPagePDF } from './PDFComponent/CoverPagePDF';
import { blobToBase64 } from '../utils/fileUtils';
import { PDFViewer } from '@react-pdf/renderer';
import CoverPageGenerator from './Cover';
import StepperPage from '../components/Stepper'; // Adjust path as needed

import ConstructionEstimateComponent from './ConstructionEstimate';

const API_BASE_URL = 'https://24.101.103.87:8082/api';

const BackEstimate = () => {
  const navigate = useNavigate();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedDocument, setSelectedDocument] = useState('bankEstimate');
  const [selectedComponents, setSelectedComponents] = useState({
    abstract: true,
    coverPage: true
  });
  const [abstractItems, setAbstractItems] = useState([]);
  const [currentStep, setCurrentStep] = useState(7); 
  const [constructionEstimate, setConstructionEstimate] = useState(null);
  const [workInfo, setWorkInfo] = useState({
    nameOfWork: '',
    workOrderId: '',
    revisionNumber: '',
    area: '',
    ssr: ''
  });
  
   const jwtToken = localStorage.getItem('authToken');

  const documentOptions = [
    { value: 'bankEstimate', label: 'Bank Estimate', icon: FileCheck },
    { value: 'mts', label: 'Measurement Sheet (MTS)', icon: FileText }
  ];

  useEffect(() => {
    const loadWorkInfo = () => {
      setWorkInfo({
        nameOfWork: localStorage.getItem('pdfWorkName') || localStorage.getItem('nameOfWork') || 'Measurement Sheet',
        workOrderId: localStorage.getItem('pdfWorkOrderId') || localStorage.getItem('autogenerated') || '',
        revisionNumber: localStorage.getItem('pdfRevisionNumber') || localStorage.getItem('reviseno') || '1.0',
        area: localStorage.getItem('abstractArea') || '900',
        ssr: localStorage.getItem('abstractSSR') || ''
      });
    };

   const loadConstructionEstimate = () => {
      try {
        const ceData = localStorage.getItem('constructionEstimate');
        if (ceData) {
          setConstructionEstimate(JSON.parse(ceData));
        }
      } catch (err) {
        console.error('Error loading construction estimate:', err);
      }
    };
      const loadAbstractItems = () => {
      try {
        const abstractData = localStorage.getItem('abstractItems');
        if (abstractData) {
          setAbstractItems(JSON.parse(abstractData));
        }
      } catch (err) {
        console.error('Error loading abstract items:', err);
      }
    };

     loadWorkInfo();
    loadConstructionEstimate();
    loadAbstractItems();
    fetchItems();
  }, []);
  const handleNextStep = (step) => {
  if (currentStep === 1) {
    if (!workName.trim()) {
      toast.error("Please enter the 'Name of Work' before proceeding!");
      return;
    }
    if (!selectedState.trim()) {
      toast.error("Please Select the 'State' before proceeding!");
      return;
    }
    if (!selectedDept.trim()) {
      toast.error("Please Select the 'Department' before proceeding!");
      return;
    }
    toast.success("Step 1 completed successfully!");
  }
  
  setCurrentStep(step);
};

// Add the handlePrevStep function
const handlePrevStep = (step) => {
  setCurrentStep(step);
  toast.info("Going back to previous step");
};

 const fetchMeasurements = async (itemId) => {
    try {
      const res = await fetch(`${API_BASE_URL}/txn-items-mts/ByItemId/${itemId}`, {
        headers: { Authorization: `Bearer ${jwtToken}` }
      });
      
      if (!res.ok) {
        throw new Error(`Failed to fetch measurements. Status: ${res.status}`);
      }
      
      return await res.json();
    } catch (err) {
      console.error(`Error fetching measurements for item ${itemId}:`, err);
      return [];
    }
  };
 
  const fetchItems = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const subRecordCache = localStorage.getItem('subRecordCache');
      
      if (!subRecordCache) {
        setError("No measurement data found in local storage");
        setLoading(false);
        return;
      }
      
      let parsedItems;
      try {
        const itemsObject = JSON.parse(subRecordCache);
        
        if (Array.isArray(itemsObject)) {
          parsedItems = itemsObject;
        } else if (typeof itemsObject === 'object') {
          parsedItems = Object.values(itemsObject).flat();
        } else {
          throw new Error("Invalid data format in subRecordCache");
        }
      } catch (parseErr) {
        console.error("Error parsing subRecordCache:", parseErr);
        setError("Invalid measurement data format in local storage");
        setLoading(false);
        return;
      }
      
      const detailedItems = await Promise.all(
        parsedItems.map(async (item) => {
          if (item.measurements && Array.isArray(item.measurements)) {
            return item;
          }
          const measurements = await fetchMeasurements(item.id);
          return { ...item, measurements };
        })
      );
      
      setItems(detailedItems);
    } catch (err) {
      console.error("Error fetching item details:", err);
      setError("Failed to load measurement data");
    } finally {
      setLoading(false);
    }
  };


  const handleComponentToggle = (component) => {
    setSelectedComponents(prev => ({
      ...prev,
      [component]: !prev[component]
    }));
  };


  const ensureCoverPageData = async () => {
    try {
      const savedCoverPageData = localStorage.getItem('coverPageData');
      if (savedCoverPageData) {
        const coverPageData = JSON.parse(savedCoverPageData);
        
        if (coverPageData.estimateCost && coverPageData.workName) {
          console.log("Using saved cover page data:", coverPageData);
          
          const constructionEstimateData = {
            grandTotal: parseFloat(coverPageData.estimateCost) || 0,
            workOrderId: workInfo.workOrderId,
            workName: coverPageData.workName,
            area: workInfo.area || '900',
            ssr: coverPageData.year || workInfo.ssr || '',
            items: items.length,
            revisionNumber: workInfo.revisionNumber,
            coverPageData: coverPageData
          };
          
          setConstructionEstimate(constructionEstimateData);
          localStorage.setItem("constructionEstimate", JSON.stringify(constructionEstimateData));
          
          localStorage.setItem("abstractWorkName", coverPageData.workName);
          localStorage.setItem("abstractWorkOrderId", workInfo.workOrderId);
          localStorage.setItem("abstractArea", workInfo.area || "900");
          localStorage.setItem("abstractSSR", coverPageData.year || workInfo.ssr || "");
          
          return constructionEstimateData;
        }
      }
      
      if (constructionEstimate && constructionEstimate.grandTotal !== undefined) {
        return constructionEstimate;
      }
      
      let grandTotal = 0;
      
      for (const item of items) {
        const quantity = Array.isArray(item.measurements) 
          ? item.measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0) 
          : 0;
        
        const amount = quantity * (parseFloat(item.labourRate) || 0);
        grandTotal += amount;
      }
      
      const newConstructionEstimate = {
        grandTotal: grandTotal || 0,
        workOrderId: workInfo.workOrderId,
        workName: workInfo.nameOfWork,
        area: workInfo.area || '900',
        ssr: workInfo.ssr || '',
        items: items.length,
        revisionNumber: workInfo.revisionNumber
      };
      
      setConstructionEstimate(newConstructionEstimate);
      localStorage.setItem("constructionEstimate", JSON.stringify(newConstructionEstimate));
      
      localStorage.setItem("abstractWorkName", workInfo.nameOfWork);
      localStorage.setItem("abstractWorkOrderId", workInfo.workOrderId);
      localStorage.setItem("abstractArea", workInfo.area || "900");
      localStorage.setItem("abstractSSR", workInfo.ssr || "");
      
      return newConstructionEstimate;
    } catch (error) {
      console.error("Error ensuring cover page data:", error);
      throw new Error(`Failed to prepare cover page data: ${error.message}`);
    }
  };

  const generateCombinedPDF = async () => {
  try {
    if (!selectedComponents.abstract && !selectedComponents.coverPage) {
      toast.error("Please select at least one component to include in the PDF");
      return;
    }

    const { nameOfWork, workOrderId, revisionNumber } = workInfo;
    const fileName = `${workOrderId || 'document'}_${revisionNumber || '1'}.pdf`;
    const loadingToast = toast.loading('Generating PDF...');

    const documentComponents = [];
    
    if (selectedComponents.coverPage) {
      try {
        // Get saved cover page data or use defaults
        const savedCoverPageData = localStorage.getItem('coverPageData');
        let coverPageData = {};
        
        if (savedCoverPageData) {
          try {
            coverPageData = JSON.parse(savedCoverPageData);
            console.log("Loaded complete cover page data:", coverPageData);
          } catch (parseError) {
            console.error("Error parsing cover page data:", parseError);
            coverPageData = {};
          }
        }

        // Calculate estimate cost if not available
        let estimateCost = 0;
        if (coverPageData.estimateCost) {
          estimateCost = parseFloat(coverPageData.estimateCost) || 0;
        } else if (constructionEstimate && constructionEstimate.grandTotal) {
          estimateCost = constructionEstimate.grandTotal;
        } else {
          // Calculate from items if needed
          for (const item of items) {
            const quantity = Array.isArray(item.measurements) 
              ? item.measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0) 
              : 0;
            const amount = quantity * (parseFloat(item.labourRate) || 0);
            estimateCost += amount;
          }
        }

        // Prepare all the props for CoverPagePDF
        const coverPageProps = {
          companyLogo: coverPageData.companyLogo || null,
          companyName: coverPageData.companyName || 'Company Name Not Set',
          companyAddress: coverPageData.address || coverPageData.companyAddress || 'Address Not Set',
          workName: coverPageData.workName || nameOfWork || 'Work Name Not Set',
          workOrderId: workOrderId || 'WO-001',
          revisionNumber: revisionNumber || '1',
          clientName: coverPageData.clientName || 'Client Name Not Set',
          propertyNo: coverPageData.propertyNo || 'Property No Not Set',
          propertyAddress: coverPageData.propertyAddress || 'Property Address Not Set',
          estimateCost: estimateCost,
          sorYear: coverPageData.year || coverPageData.sorYear || new Date().getFullYear().toString(),
          area: workInfo.area || coverPageData.area || '900',
          ssr: coverPageData.year || coverPageData.ssr || workInfo.ssr || ''
        };

        console.log("=== Final Cover Page Props Being Sent to PDF ===", coverPageProps);

        // Always add cover page component with all available data
        documentComponents.push(
          <CoverPagePDF 
            key="cover-page"
            {...coverPageProps}
          />
        );
        
        console.log("Cover page added to PDF successfully");
        
      } catch (error) {
        console.error("Error preparing cover page:", error);
        toast.error(`Cover page error: ${error.message}`);
      }
    }
    
    if (selectedComponents.abstract) {
      try {
        const abstractData = await prepareAbstractData();
        
        if (abstractData && abstractData.length > 0) {
          // Ensure all required props are provided with safe defaults
          const safeWorkInfo = {
            workOrderId: workOrderId || 'WO-001',
            nameOfWork: nameOfWork || 'Construction Work',
            area: workInfo.area || '900',
            ssr: workInfo.ssr || '',
            revisionNumber: revisionNumber || '1.0'
          };

          documentComponents.push(
            <AbstractPDF 
              key="abstract"
              workOrderId={safeWorkInfo.workOrderId} 
              workName={safeWorkInfo.nameOfWork} 
              items={abstractData}
              workInfo={safeWorkInfo}
            />
          );
          console.log("Abstract added to PDF");
        }
      } catch (error) {
        console.error("Error preparing abstract:", error);
        toast.error("Failed to prepare abstract data");
      }
    }
    
    if (documentComponents.length === 0) {
      toast.dismiss(loadingToast);
      toast.error("No valid PDF components to generate. Please ensure you have created the required data first.");
      return;
    }

    const CombinedDocument = () => (
      <Document>
        {documentComponents}
      </Document>
    );

    console.log(`Generating PDF with ${documentComponents.length} components`);
    
    const blob = await pdf(<CombinedDocument />).toBlob();
    
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = fileName;
    link.click();
    
    URL.revokeObjectURL(link.href);
    
    toast.dismiss(loadingToast);
    toast.success('PDF downloaded successfully!');
    
    console.log("PDF generation completed successfully");
  } catch (err) {
    console.error("Error generating combined PDF:", err);
    toast.error(`Failed to generate PDF: ${err.message}`);
  }
};
const handleStepperClick = (stepId) => {
  if (stepId < currentStep) {
    setCurrentStep(stepId); // Go back freely
  } else {
    handleNextStep(stepId); // Apply forward step validation
  }
};

  const prepareAbstractData = async () => {
    try {
      let itemsToProcess = [];
      
      if (Array.isArray(items)) {
        itemsToProcess = items;
      } else if (typeof items === 'object' && items !== null) {
        const allSubworkIds = Object.keys(items);
        
        if (allSubworkIds.length === 0) {
          throw new Error("No subworks or items found to generate abstract");
        }
        
        itemsToProcess = allSubworkIds.flatMap(subworkId => items[subworkId] || []);
      }
      
      if (itemsToProcess.length === 0) {
        throw new Error("No items found to generate abstract");
      }
      
      const processedItems = await Promise.all(
        itemsToProcess.map(async (item) => {
          let measurements = item.measurements;
          
          if (!measurements || !Array.isArray(measurements)) {
            try {
              measurements = await fetchMeasurements(item.id);
            } catch (err) {
              console.error(`Error fetching measurements for item ${item.id}:`, err);
              measurements = [];
            }
          }
          
          const quantity = Array.isArray(measurements) 
            ? measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0) 
            : 0;
          
          // Ensure all required fields are present with safe defaults
          return { 
            ...item, 
            id: item.id || Math.random().toString(36).substr(2, 9),
            itemNo: item.itemNo || item.itemNumber || 'N/A',
            descriptionOfItem: item.descriptionOfItem || item.description || 'No description',
            unit: item.unit || 'Nos',
            labourRate: item.labourRate || item.rate || 0,
            measurements: Array.isArray(measurements) ? measurements : [],
            quantity: quantity,
            amount: quantity * (parseFloat(item.labourRate || item.rate) || 0)
          };
        })
      );
      
      setAbstractItems(processedItems);
      localStorage.setItem("abstractItems", JSON.stringify(processedItems));
      
      localStorage.setItem("abstractWorkName", workInfo.nameOfWork);
      localStorage.setItem("abstractWorkOrderId", workInfo.workOrderId);
      localStorage.setItem("abstractArea", workInfo.area || "900");
      localStorage.setItem("abstractSSR", workInfo.ssr || "");
      
      return processedItems;
    } catch (error) {
      console.error("Error preparing abstract data:", error);
      throw error;
    }
  };

  // Auto-prepare data when components are selected
  useEffect(() => {
    if (items.length > 0) {
      if (selectedComponents.abstract && abstractItems.length === 0) {
        prepareAbstractData().catch(console.error);
      }
      
      if (selectedComponents.coverPage && !constructionEstimate) {
        ensureCoverPageData().catch(console.error);
      }
    }
  }, [selectedComponents, items]);

  const renderBankEstimateContent = () => {
    if (loading) {
      return (
        <div className="text-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading measurement data...</p>
        </div>
      );
    }

    if (error) {
      return (
        
        <div className="text-center py-8">
          
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 max-w-md mx-auto">
            <div className="text-red-600 mb-4">
              <X className="mx-auto mb-2" size={32} />
              <p className="font-medium">{error}</p>
            </div>
            <button 
              onClick={fetchItems} 
              className="bg-red-600 text-white px-6 py-2 rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      );
    }

    return (
      <div className="space-y-8">
        {/* Component Selection Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Cover Page Card */}
          <div 
            className={`group relative overflow-hidden rounded-xl border-2 transition-all duration-300 cursor-pointer ${
              selectedComponents.coverPage 
                ? 'border-blue-500 bg-blue-50 shadow-lg' 
                : 'border-gray-200 bg-white hover:border-blue-300 hover:shadow-md'
            }`}
            onClick={() => handleComponentToggle('coverPage')}
          >
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className={`p-3 rounded-lg ${selectedComponents.coverPage ? 'bg-blue-500' : 'bg-gray-100'}`}>
                    <FileCheck className={`${selectedComponents.coverPage ? 'text-white' : 'text-gray-600'}`} size={24} />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">Cover Page</h3>
                    <p className="text-sm text-gray-500">Project overview & details</p>
                  </div>
                </div>
                <div className={`w-6 h-6 rounded-full flex items-center justify-center transition-colors ${
                  selectedComponents.coverPage ? 'bg-blue-500' : 'bg-gray-300'
                }`}>
                  {selectedComponents.coverPage && <Check size={16} className="text-white" />}
                </div>
              </div>
              <div className="space-y-2 text-sm text-gray-600">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Company information</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Project details</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Cost estimate</span>
                </div>
              </div>
            </div>
            {selectedComponents.coverPage && (
              <div className="absolute top-2 right-2">
                <div className="bg-blue-500 text-white text-xs px-2 py-1 rounded-full">
                  Selected
                </div>
              </div>
            )}
          </div>

          {/* Abstract Card */}
          <div 
            className={`group relative overflow-hidden rounded-xl border-2 transition-all duration-300 cursor-pointer ${
              selectedComponents.abstract 
                ? 'border-purple-500 bg-purple-50 shadow-lg' 
                : 'border-gray-200 bg-white hover:border-purple-300 hover:shadow-md'
            }`}
            onClick={() => handleComponentToggle('abstract')}
          >
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className={`p-3 rounded-lg ${selectedComponents.abstract ? 'bg-purple-500' : 'bg-gray-100'}`}>
                    <FileText className={`${selectedComponents.abstract ? 'text-white' : 'text-gray-600'}`} size={24} />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">Abstract</h3>
                    <p className="text-sm text-gray-500">Cost breakdown summary</p>
                  </div>
                </div>
                <div className={`w-6 h-6 rounded-full flex items-center justify-center transition-colors ${
                  selectedComponents.abstract ? 'bg-purple-500' : 'bg-gray-300'
                }`}>
                  {selectedComponents.abstract && <Check size={16} className="text-white" />}
                </div>
              </div>
              <div className="space-y-2 text-sm text-gray-600">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
                  <span>Item-wise costs</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
                  <span>Quantity analysis</span>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
                  <span>Total estimation</span>
                </div>
              </div>
            </div>
            {selectedComponents.abstract && (
              <div className="absolute top-2 right-2">
                <div className="bg-purple-500 text-white text-xs px-2 py-1 rounded-full">
                  Selected
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Preview Sections */}
        <div className="space-y-6">
          {selectedComponents.coverPage && (
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200 overflow-hidden">
              <div className="bg-white border-b border-blue-200 p-4">
                <div className="flex items-center space-x-2">
                  <Eye className="text-blue-600" size={20} />
                  <h3 className="font-semibold text-gray-800">Cover Page Preview</h3>
                </div>
              </div>
              <div className="p-6">
                <CoverPageGenerator />
              </div>
            </div>
          )}

          {selectedComponents.abstract && (
            <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-xl border border-purple-200 overflow-hidden">
              <div className="bg-white border-b border-purple-200 p-4">
                <div className="flex items-center space-x-2">
                  <Eye className="text-purple-600" size={20} />
                  <h3 className="font-semibold text-gray-800">Abstract Preview</h3>
                </div>
              </div>
              <div className="p-6">
                <ConstructionEstimateComponent />
              </div>
            </div>
          )}
        </div>

        {/* Action Button */}
        <div className="flex justify-center pt-6">
          <button 
            onClick={generateCombinedPDF}
            className="group relative bg-gradient-to-r from-blue-600 to-indigo-600 text-white py-4 px-8 rounded-xl hover:from-blue-700 hover:to-indigo-700 transition-all duration-300 flex items-center justify-center text-base shadow-lg hover:shadow-xl transform hover:-translate-y-1"
            disabled={loading || (!selectedComponents.coverPage && !selectedComponents.abstract)}
          >
            <Download className="mr-3 group-hover:animate-bounce" size={20} />
            <span className="font-semibold">Generate Bank Estimate PDF</span>
            <div className="absolute inset-0 rounded-xl bg-white opacity-0 group-hover:opacity-10 transition-opacity"></div>
          </button>
        </div>
      </div>
    );
  };

  const renderMTSContent = () => {
    if (loading) {
      return (
        <div className="text-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading measurement data...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="text-center py-8">
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 max-w-md mx-auto">
            <div className="text-red-600 mb-4">
              <X className="mx-auto mb-2" size={32} />
              <p className="font-medium">{error}</p>
            </div>
            <button 
              onClick={fetchItems} 
              className="bg-red-600 text-white px-6 py-2 rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      );
    }

    if (!items || items.length === 0) {
      return (
        <div className="text-center py-12">
          <FileText className="mx-auto mb-4 text-gray-400" size={48} />
          <p className="text-gray-600 text-lg">No measurement data available</p>
        </div>
      );
    }
   const renderStepperSection = () => (
  <div className="mb-6">
    <div className="mb-6 mt-2 p-4 border border-gray-300 rounded bg-white shadow">
      <StepperPage 
        currentStep={currentStep}
        onStepClick={(stepId) => {
          if (stepId < currentStep) {
            handlePrevStep(stepId); // Go back freely
          } else {
            handleNextStep(stepId); // Apply forward step validation
          }
        }} 
      />
    </div>
  </div>
);
     
    return (
      <div className="space-y-6">
       
          <div className="mb-6">
                              </div>
        <div className="bg-gradient-to-r from-indigo-50 to-blue-50 rounded-xl border border-indigo-200 overflow-hidden">
          <div className="bg-white border-b border-indigo-200 p-4">
            <div className="flex items-center space-x-2">
              <Eye className="text-indigo-600" size={20} />
              <h3 className="font-semibold text-gray-800">Measurement Sheet Preview</h3>
            </div>
          </div>
          <div className="p-6">
            <div className="h-96 rounded-lg overflow-hidden shadow-inner">
              <PDFViewer width="100%" height="100%" style={{ border: 'none', borderRadius: '8px' }}>
                <Document>
                  <MeasurementPDF 
                    workOrderId={workInfo.workOrderId} 
                    nameOfWork={workInfo.nameOfWork} 
                    items={items} 
                  />
                </Document>
              </PDFViewer>
            </div>
          </div>
        </div>
        
        <div className="flex justify-center">
          <button 
            onClick={() => {
              const generateMTSPDF = async () => {
                try {
                  const { nameOfWork, workOrderId, revisionNumber } = workInfo;
                  const fileName = `MTS_${workOrderId || 'document'}_${revisionNumber || '1'}.pdf`;
                  const loadingToast = toast.loading('Generating MTS PDF...');

                  const MTSDocument = () => (
                    <Document>
                      <MeasurementPDF 
                        workOrderId={workOrderId || 'WO-001'} 
                        nameOfWork={nameOfWork || 'Construction Work'} 
                        items={items} 
                      />
                    </Document>
                  );

                  const blob = await pdf(<MTSDocument />).toBlob();
                  
                  const link = document.createElement('a');
                  link.href = URL.createObjectURL(blob);
                  link.download = fileName;
                  link.click();
                  
                  URL.revokeObjectURL(link.href);
                  
                  toast.dismiss(loadingToast);
                  toast.success('MTS PDF downloaded successfully!');
                } catch (err) {
                  console.error("Error generating MTS PDF:", err);
                  toast.error(`Failed to generate MTS PDF: ${err.message}`);
                }
              };
              generateMTSPDF();
            }}
            className="group relative bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-4 px-8 rounded-xl hover:from-indigo-700 hover:to-purple-700 transition-all duration-300 flex items-center justify-center shadow-lg hover:shadow-xl transform hover:-translate-y-1"
            disabled={loading}
          >
            <Download className="mr-3 group-hover:animate-bounce" size={20} />
            <span className="font-semibold">Download MTS PDF</span>
            <div className="absolute inset-0 rounded-xl bg-white opacity-0 group-hover:opacity-10 transition-opacity"></div>
          </button>
        </div>
      </div>
    );
  };
return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          
       
           <div className="mb-4">
            <StepperPage 
              currentStep={currentStep} 
              onStepClick={handleStepperClick}
            />
          </div>
        </div>

        {/* Document Type Selector */}
        <div className="mb-8">
          <div className="bg-white rounded-xl shadow-lg p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Select Document Type</h2>
            <div className="flex flex-wrap gap-4">
              {documentOptions.map((option) => {
                const IconComponent = option.icon;
                return (
                  <button
                    key={option.value}
                    onClick={() => setSelectedDocument(option.value)}
                    className={`flex items-center space-x-3 px-6 py-4 rounded-lg border-2 transition-all duration-300 ${
                      selectedDocument === option.value
                        ? 'border-blue-500 bg-blue-50 text-blue-700'
                        : 'border-gray-200 bg-white text-gray-700 hover:border-blue-300 hover:bg-blue-50'
                    }`}
                  >
                    <IconComponent size={24} />
                    <span className="font-medium">{option.label}</span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Content Area */}
        <div className="bg-white rounded-xl shadow-lg p-8">
          {selectedDocument === 'bankEstimate' ? renderBankEstimateContent() : renderMTSContent()}
        </div>

        {/* Footer */}
        <div className="mt-8 text-center text-gray-500 text-sm">
          <p>© 2024 Construction Management System. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
};

export default BackEstimate;