import React, { useEffect, useState } from 'react';
import Stepper from '../components/Stepper';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { FileText, Check, Download, ChevronDown, X, Eye, FileCheck } from 'lucide-react';

import { 
  Document, 
  Page, 
  Text, 
  View, 
  StyleSheet, 
  PDFDownloadLink, 
  Font,
  pdf 
} from '@react-pdf/renderer';
import { MeasurementPDF } from './PDFComponent/MeasurementPDF';
import { AbstractPDF } from './PDFComponent/AbstractPDF';
import { CoverPagePDF } from './PDFComponent/CoverPagePDF';
import { blobToBase64 } from '../utils/fileUtils';
import { PDFViewer } from '@react-pdf/renderer';
import CoverPageGenerator from './Cover';
import StepperPage from '../components/Stepper'; // Adjust path as needed
import { PDFDocument } from 'pdf-lib';
import ConstructionEstimateComponent from './ConstructionEstimate';

const API_BASE_URL = 'https://24.101.103.87:8082/api';

const BackEstimate = () => {
  const navigate = useNavigate();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedDocument, setSelectedDocument] = useState('bankEstimate');
  const [selectedComponents, setSelectedComponents] = useState({
    abstract: true,
    coverPage: true
  });
  
  const [abstractItems, setAbstractItems] = useState([]);
  const [currentStep, setCurrentStep] = useState(7);
   const [uploadedFiles, setUploadedFiles] = useState([]);
   const [isUploading, setIsUploading] = useState(false); // Upload state

  const [constructionEstimate, setConstructionEstimate] = useState(null);
  const [workInfo, setWorkInfo] = useState({
    nameOfWork: '',
    workOrderId: '',
    revisionNumber: '',
    area: '',
    ssr: ''
  });
  const [signatures, setSignatures] = useState({
  preparedBy: '',
  checkedBy: ''
});
   const jwtToken = localStorage.getItem('authToken');

  const documentOptions = [
    { value: 'bankEstimate', label: 'Bank Estimate', icon: FileCheck },
    { value: 'mts', label: 'Measurement Sheet (MTS)', icon: FileText }
  ];

  useEffect(() => {
  const loadWorkInfo = () => {
    setWorkInfo({
      nameOfWork: localStorage.getItem('pdfWorkName') || localStorage.getItem('nameOfWork') || 'Measurement Sheet',
      workOrderId: localStorage.getItem('pdfWorkOrderId') || localStorage.getItem('autogenerated') || '',
      revisionNumber: localStorage.getItem('pdfRevisionNumber') || localStorage.getItem('reviseno') || '1.0',
      area: localStorage.getItem('abstractArea') || '900',
      ssr: localStorage.getItem('abstractSSR') || ''
    });
  };

    const loadConstructionEstimate = () => {
    try {
      const ceData = localStorage.getItem('constructionEstimate');
      if (ceData) {
        setConstructionEstimate(JSON.parse(ceData));
      }
    } catch (err) {
      console.error('Error loading construction estimate:', err);
    }
  };

       const loadAbstractItems = () => {
    try {
      const abstractData = localStorage.getItem('abstractItems');
      if (abstractData) {
        setAbstractItems(JSON.parse(abstractData));
      }
    } catch (err) {
      console.error('Error loading abstract items:', err);
    }
  };
   const loadSignatureData = () => {
    try {
      const preparedBy = localStorage.getItem('preparedBySignature') || 
                        localStorage.getItem('preparedBy') || '';
      const checkedBy = localStorage.getItem('checkedBySignature') || 
                       localStorage.getItem('checkedBy') || '';
      
      setSignatures({
        preparedBy,
        checkedBy
      });
    } catch (error) {
      console.error("Error loading signature data:", error);
    }
  };

     loadWorkInfo();
    loadConstructionEstimate();
    loadAbstractItems();
    loadSignatureData(); 
    fetchItems();
  }, []);
  const base64ToArrayBuffer = (base64) => {
  try {
    // Remove data URL prefix if present
    const base64Data = base64.includes(',') ? base64.split(',')[1] : base64;
    
    // Convert base64 to binary string
    const binaryString = window.atob(base64Data);
    const len = binaryString.length;
    const bytes = new Uint8Array(len);
    
    for (let i = 0; i < len; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    
    return bytes.buffer;
  } catch (error) {
    console.error('Error converting base64 to ArrayBuffer:', error);
    return null;
  }
};
  const handleNextStep = (step) => {
  if (currentStep === 1) {
    if (!workName.trim()) {
      toast.error("Please enter the 'Name of Work' before proceeding!");
      return;
    }
    if (!selectedState.trim()) {
      toast.error("Please Select the 'State' before proceeding!");
      return;
    }
    if (!selectedDept.trim()) {
      toast.error("Please Select the 'Department' before proceeding!");
      return;
    }
    toast.success("Step 1 completed successfully!");
  }
  
  setCurrentStep(step);
};

const loadAuxiliaryWorks = () => {
  try {
    const stored = localStorage.getItem('dynamicAdditions');
    if (stored) {
      const parsed = JSON.parse(stored);
      return Object.keys(parsed).map(key => ({
        description: parsed[key].label,
        percentage: parsed[key].percent,
        isPercentage: true,
        amount: 0,
        customDescription: parsed[key].label
      }));
    }
    return [];
  } catch (error) {
    console.error('Error loading auxiliary works:', error);
    return [];
  }
};
const loadGstPercentage = () => {
  try {
    const storedGst = localStorage.getItem('gstPercentage');
    return storedGst ? parseFloat(storedGst) : 18;
  } catch (error) {
    console.error('Error loading GST percentage:', error);
    return 18;
  }
};
const generateAbstractPDF = () => {
  try {
    // Load auxiliary works and GST from localStorage
    const auxiliaryWorks = loadAuxiliaryWorks();
    const gstPercentage = loadGstPercentage();
    
    // Prepare items data from abstractItems
    const pdfItems = abstractItems.map((item, index) => ({
      srNo: index + 1,
      description: item.descriptionOfItem || item.description || 'No description',
      itemNo: item.itemNo || item.itemNumber || 'N/A',
      quantity: item.quantity || 0,
      rate: item.labourRate || item.rate || 0,
      unit: item.unit || 'Nos',
      amount: (item.quantity || 0) * (item.labourRate || item.rate || 0)
    }));

    // Calculate totals
    const calculateTotals = () => {
      const itemsTotal = pdfItems.reduce((sum, item) => sum + item.amount, 0);
      
      // Calculate auxiliary works amounts
      const processedAuxWorks = auxiliaryWorks.map(aux => ({
        ...aux,
        amount: aux.isPercentage ? (itemsTotal * aux.percentage) / 100 : aux.amount
      }));
      
      const auxTotal = processedAuxWorks.reduce((sum, aux) => sum + aux.amount, 0);
      const subtotal = itemsTotal + auxTotal;
      const gstAmount = (subtotal * gstPercentage) / 100;
      const grandTotal = subtotal + gstAmount;
      
      return {
        itemsTotal,
        auxTotal,
        subtotal,
        gstAmount,
        grandTotal,
        processedAuxWorks
      };
    };

    const totals = calculateTotals();
    const { nameOfWork, workOrderId, revisionNumber } = workInfo;
    
    const printWindow = window.open('', '_blank');
    
    if (!printWindow) {
      toast.error('Please allow pop-ups to generate PDF');
      return;
    }
    
    printWindow.document.write(`
      <html>
        <head>
          <title>Abstract - ${workOrderId}_${revisionNumber}</title>
          <style>
            @page {
              size: A4;
              margin: 15mm;
            }
            
            * {
              box-sizing: border-box;
            }
            
            body {
              font-family: Arial, sans-serif;
              margin: 0;
              padding: 10px;
              color: #333;
              font-size: 11px;
              line-height: 1.3;
              background-color: white;
            }
            
            .container {
              max-width: 100%;
              margin: 0 auto;
            }
            
            h1 {
              text-align: center;
              margin: 0 0 15px 0;
              font-size: 20px;
              font-weight: bold;
              page-break-after: avoid;
            }
            
            .work-name {
              text-align: center;
              margin: 0 0 15px 0;
              font-size: 16px;
              font-weight: bold;
              color: #666;
              text-transform: uppercase;
              page-break-after: avoid;
            }
            
            .header-info {
              display: flex;
              justify-content: space-between;
              margin-bottom: 15px;
              font-weight: bold;
              page-break-after: avoid;
            }
            
            .main-table {
              width: 100%;
              border-collapse: collapse;
              margin-bottom: 0;
              font-size: 10px;
              background-color: white;
              page-break-inside: auto;
            }
            
            .main-table th,
            .main-table td {
              border: 1px solid #000;
              padding: 4px;
              text-align: left;
              vertical-align: top;
              background-color: white;
            }
            
            .main-table th {
              background-color: #f5f5f5 !important;
              font-weight: bold;
              text-align: center;
              page-break-after: avoid;
            }
            
            .main-table tbody tr {
              page-break-inside: avoid;
            }
            
            .main-table tbody td {
              background-color: white !important;
            }
            
            .main-table tfoot td {
              background-color: #f9fafb !important;
              font-weight: bold;
            }
            
            .main-table tfoot tr {
              page-break-inside: avoid;
            }
            
            .text-center {
              text-align: center !important;
            }
            
            .text-right {
              text-align: right !important;
            }
            
            .col-sr { width: 5%; }
            .col-item { width: 8%; }
            .col-desc { width: 45%; }
            .col-qty { width: 10%; }
            .col-rate { width: 10%; }
            .col-unit { width: 10%; }
            .col-amount { width: 12%; }
            
            .grand-total-row {
              font-weight: bold !important;
              font-size: 12px !important;
              background-color: #e5e7eb !important;
            }
            
            .grand-total-row td {
              background-color: #e5e7eb !important;
              font-weight: bold !important;
              font-size: 12px !important;
            }
            
            .signature-section {
              margin-top: 30px;
              margin-bottom: 20px;
              display: flex;
              justify-content: space-between;
              align-items: flex-end;
              page-break-inside: avoid;
              page-break-before: avoid;
            }
            
            .signature-box {
              text-align: center;
              min-width: 180px;
              background-color: white;
              padding: 6px;
            }
            
            .signature-line {
              border-bottom: 1px solid #9ca3af;
              height: 50px;
              display: flex;
              align-items: flex-end;
              justify-content: center;
              padding-bottom: 6px;
              margin-bottom: 6px;
            }
            
            .signature-label {
              font-weight: bold;
              margin-bottom: 3px;
              font-size: 10px;
            }
            
            .signature-name {
              font-weight: bold;
              font-size: 10px;
            }
            
            @media print {
              @page {
                size: A4;
                margin: 10mm;
              }
              
              body {
                margin: 0;
                padding: 5px;
                font-size: 10px;
                line-height: 1.2;
              }
              
              button {
                display: none !important;
              }
              
              .no-print {
                display: none !important;
              }
            }
          </style>
        </head>
        <body>
          <button onclick="window.print()" class="no-print" style="padding: 6px 12px; background-color: #4CAF50; color: white; border: none; cursor: pointer; float: right; margin-bottom: 15px; border-radius: 3px; font-size: 12px;">Print / Save as PDF</button>
          
          <div class="container">
            <h1>ABSTRACT OF ESTIMATE</h1>
            
            ${nameOfWork ? `<div class="work-name">Work: ${nameOfWork.toUpperCase()}</div>` : ''}
            
            <div class="header-info">
              <div>Work Order ID: ${workOrderId || 'N/A'}</div>
              <div>Revision: ${revisionNumber || '1.0'}</div>
              <div>Date: ${new Date().toLocaleDateString('en-IN')}</div>
            </div>
            
            <table class="main-table">
              <thead>
                <tr>
                  <th class="col-sr">Sr. No.</th>
                  <th class="col-desc">Item of work</th>
                  <th class="col-item">SSR Item No.</th>
                  <th class="col-qty">Qty</th>
                  <th class="col-rate">Rate</th>
                  <th class="col-unit">Unit</th>
                  <th class="col-amount">Amount</th>
                </tr>
              </thead>
              <tbody>
                ${pdfItems.map((item) => `
                  <tr>
                    <td class="text-center">${item.srNo}</td>
                    <td>${item.description}</td>
                    <td class="text-center">${item.itemNo}</td>
                    <td class="text-right">${parseFloat(item.quantity).toFixed(2)}</td>
                    <td class="text-right">${parseFloat(item.rate).toFixed(2)}</td>
                    <td class="text-center">${item.unit}</td>
                    <td class="text-right">${item.amount.toFixed(2)}</td>
                  </tr>
                `).join('')}
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="6" class="text-right">Main Items Total:</td>
                  <td class="text-right">${totals.itemsTotal.toLocaleString('en-IN', {
                    style: 'currency',
                    currency: 'INR',
                    minimumFractionDigits: 2
                  })}</td>
                </tr>
                ${totals.processedAuxWorks.map((aux) => `
                  <tr>
                    <td colspan="6" class="text-right">
                      ${aux.description}${aux.isPercentage ? ` (${aux.percentage}%)` : ' (Fixed Amount)'}:
                    </td>
                    <td class="text-right">${aux.amount.toLocaleString('en-IN', {
                      style: 'currency',
                      currency: 'INR',
                      minimumFractionDigits: 2
                    })}</td>
                  </tr>
                `).join('')}
                <tr>
                  <td colspan="6" class="text-right">Subtotal:</td>
                  <td class="text-right">${totals.subtotal.toLocaleString('en-IN', {
                    style: 'currency',
                    currency: 'INR',
                    minimumFractionDigits: 2
                  })}</td>
                </tr>
                <tr>
                  <td colspan="6" class="text-right">GST (${gstPercentage}%):</td>
                  <td class="text-right">${totals.gstAmount.toLocaleString('en-IN', {
                    style: 'currency',
                    currency: 'INR',
                    minimumFractionDigits: 2
                  })}</td>
                </tr>
                <tr class="grand-total-row">
                  <td colspan="6" class="text-right">Grand Total:</td>
                  <td class="text-right">${totals.grandTotal.toLocaleString('en-IN', {
                    style: 'currency',
                    currency: 'INR',
                    minimumFractionDigits: 2
                  })}</td>
                </tr>
              </tfoot>
            </table>
            
            <div class="signature-section">
              <div class="signature-box">
                <div class="signature-line"></div>
                <p class="signature-label">Prepared By</p>
                ${signatures.preparedBy ? `<p class="signature-name">${signatures.preparedBy}</p>` : ''}
              </div>
              
              <div class="signature-box">
                <div class="signature-line"></div>
                <p class="signature-label">Checked By</p>
                ${signatures.checkedBy ? `<p class="signature-name">${signatures.checkedBy}</p>` : ''}
              </div>
            </div>
          </div>
        </body>
      </html>
    `);
    
    printWindow.document.close();
    printWindow.focus();
    
    // Set the document title for saving
    setTimeout(() => {
      printWindow.document.title = `${workOrderId || 'Abstract'}_${revisionNumber || '1.0'}`;
      printWindow.print();
    }, 1000);
    
  } catch (err) {
    console.error("Error generating Abstract PDF:", err);
    toast.error(`Failed to generate PDF: ${err.message}`);
  }
};
const uploadPDFToServer = async (pdfBlob, fileName) => {
  try {
    setIsUploading(true);
    const loadingToast = toast.loading('Uploading PDF to server...');

    // Get reviseId and workOrderId from localStorage
    const reviseId = localStorage.getItem("reviseId");
    const workOrderId = localStorage.getItem("workOrderId") || workInfo.workOrderId;
    
    // Validate blob
    if (!pdfBlob || !(pdfBlob instanceof Blob)) {
      throw new Error('Invalid PDF blob provided');
    }
    
    // Create FormData for file upload
    const formData = new FormData();
    formData.append('file', pdfBlob, fileName);
    
    // Include ID in form data if available
    if (reviseId) {
      formData.append("id", reviseId);
    }

    console.log(`Uploading ${fileName} (${pdfBlob.size} bytes) to server...`);

    const uploadResponse = await fetch(`${API_BASE_URL}/file/upload`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${jwtToken}`
        // No Content-Type header needed for FormData
      },
      body: formData
    });

    if (!uploadResponse.ok) {
      const errorText = await uploadResponse.text();
      throw new Error(`Upload failed with status: ${uploadResponse.status}. ${errorText}`);
    }

    // Handle both JSON and text responses
    const contentType = uploadResponse.headers.get("content-type");
    let uploadResult;
    
    if (contentType && contentType.includes("application/json")) {
      uploadResult = await uploadResponse.json();
      console.log("Upload success (JSON):", uploadResult);
    } else {
      const textResult = await uploadResponse.text();
      console.log("Upload success (text):", textResult);
      uploadResult = { fileName: fileName, message: textResult };
    }
    
    toast.dismiss(loadingToast);
    toast.success('PDF uploaded to server successfully!');
    
    const fileInfo = {
      fileName: fileName,
      serverFileName: uploadResult.fileName || fileName,
      uploadTime: new Date().toISOString(),
      downloadUrl: `${API_BASE_URL}/file/download/${uploadResult.fileName || fileName}`
    };
    
    setUploadedFiles(prev => [...prev, fileInfo]);

    // Update workorder status to 'completed' if workOrderId exists
    if (workOrderId) {
      try {
        console.log(`Attempting to update work order status for: ${workOrderId}`);
        
        const statusUpdateResponse = await fetch(`${API_BASE_URL}/workorders/${workOrderId}`, {
          method: "PUT",
          headers: {
            "Content-Type": "application/json",
            "Authorization": `Bearer ${jwtToken}`
          },
          body: JSON.stringify({ 
            status: "completed",
            // Add any other required fields that might be missing
            updatedAt: new Date().toISOString()
          })
        });

        if (statusUpdateResponse.ok) {
          const updateData = await statusUpdateResponse.json();
          console.log("Work order updated successfully:", updateData);
          toast.success("Work order marked as completed!");
          
          // Optional: Navigate to work list page after successful completion
          setTimeout(() => {
            navigate('/mywork');
          }, 2000);
        } else {
          const errorText = await statusUpdateResponse.text();
          console.warn("Failed to update work order status:", errorText);
          
          // Don't throw error here, just warn - PDF upload was successful
          toast.error("PDF uploaded successfully, but failed to update work order status");
          
          // Still provide download option
          triggerDownload(pdfBlob, fileName);
        }
      } catch (statusError) {
        console.error("Error updating work order status:", statusError);
        toast.error("PDF uploaded successfully, but failed to update work order status");
        
        // Still provide download option
        triggerDownload(pdfBlob, fileName);
      }
    }
    
    return fileInfo;
  } catch (error) {
    console.error('Error uploading PDF:', error);
    
    // Provide fallback download if upload fails
    if (pdfBlob && fileName) {
      try {
        triggerDownload(pdfBlob, fileName);
        toast.success('PDF downloaded locally (upload failed)');
      } catch (downloadError) {
        console.error('Fallback download also failed:', downloadError);
        toast.error(`Upload failed and download fallback failed: ${error.message}`);
      }
    } else {
      toast.error(`Failed to upload PDF: ${error.message}`);
    }
    
    throw error;
  } finally {
    setIsUploading(false);
  }
};

// Helper function to trigger download
const triggerDownload = (blob, fileName) => {
  try {
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.href = url;
    link.download = fileName;
    
    // Append to body, click, and remove
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up the URL object
    URL.revokeObjectURL(url);
    
    console.log(`Download triggered for: ${fileName}`);
  } catch (error) {
    console.error('Error triggering download:', error);
    throw error;
  }
};
// Fixed generateAbstractPDFBlob function with correct formatting and centering
const generateAbstractPDFBlob = async () => {
  try {
    // Load auxiliary works and GST from localStorage
    const auxiliaryWorks = loadAuxiliaryWorks();
    const gstPercentage = loadGstPercentage();
    
    // Prepare items data from abstractItems
    const pdfItems = abstractItems.map((item, index) => ({
      srNo: index + 1,
      description: item.descriptionOfItem || item.description || 'No description',
      itemNo: item.itemNo || item.itemNumber || 'N/A',
      quantity: item.quantity || 0,
      rate: item.labourRate || item.rate || 0,
      unit: item.smallUnit || 'Nos', // Updated to use smallUnit as requested
      amount: (item.quantity || 0) * (item.labourRate || item.rate || 0)
    }));

    // Calculate totals
    const calculateTotals = () => {
      const itemsTotal = pdfItems.reduce((sum, item) => sum + item.amount, 0);
      
      const processedAuxWorks = auxiliaryWorks.map(aux => ({
        ...aux,
        amount: aux.isPercentage ? (itemsTotal * aux.percentage) / 100 : aux.amount
      }));
      
      const auxTotal = processedAuxWorks.reduce((sum, aux) => sum + aux.amount, 0);
      const subtotal = itemsTotal + auxTotal;
      const gstAmount = (subtotal * gstPercentage) / 100;
      const grandTotal = subtotal + gstAmount;
      
      return {
        itemsTotal,
        auxTotal,
        subtotal,
        gstAmount,
        grandTotal,
        processedAuxWorks
      };
    };

    // Helper function to format currency properly
    const formatCurrency = (amount) => {
      const formattedAmount = amount.toLocaleString('en-IN', { 
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      });
      return `Rs.${formattedAmount}`;
    };

    // Helper function to format percentage with 2 decimal places
    const formatPercentage = (percentage) => {
      return parseFloat(percentage).toFixed(2);
    };

    const totals = calculateTotals();
    const { nameOfWork, workOrderId, revisionNumber } = workInfo;
    
    // Create Abstract PDF using react-pdf
    const AbstractDocument = () => (
      <Document>
        <Page size="A4" style={{ padding: 30, fontSize: 10, fontFamily: 'Helvetica' }}>
          <View style={{ textAlign: 'center', marginBottom: 20 }}>
            <Text style={{ fontSize: 18, fontWeight: 'bold' }}>ABSTRACT </Text>
            {nameOfWork && (
              <Text style={{ fontSize: 14, marginTop: 10, textTransform: 'uppercase' }}>
                Work: {nameOfWork}
              </Text>
            )}
          </View>
          
          <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 }}>
            {/* <Text>Work Order ID: {workOrderId || 'N/A'}</Text> */}
            {/* <Text>Revision: {revisionNumber || '1.0'}</Text> */}
            <Text>Date: {new Date().toLocaleDateString('en-IN')}</Text>
          </View>
          
          <View style={{ border: '1pt solid #000' }}>
            {/* Table Header */}
            <View style={{ 
              flexDirection: 'row', 
              backgroundColor: '#f5f5f5', 
              borderBottom: '1pt solid #000' 
            }}>
              <Text style={{ 
                width: '6%', 
                padding: 4, 
                textAlign: 'center', 
                borderRight: '1pt solid #000' 
              }}>Sr. No.</Text>
              <Text style={{ 
                width: '32%', 
                padding: 4, 
                textAlign: 'center', 
                borderRight: '1pt solid #000' 
              }}>Item of work</Text>
              <Text style={{ 
                width: '10%', 
                padding: 4, 
                textAlign: 'center', 
                borderRight: '1pt solid #000' 
              }}>SSR Item No.</Text>
              <Text style={{ 
                width: '9%', 
                padding: 4, 
                textAlign: 'center', 
                borderRight: '1pt solid #000' 
              }}>Qty</Text>
              <Text style={{ 
                width: '11%', 
                padding: 4, 
                textAlign: 'center', 
                borderRight: '1pt solid #000' 
              }}>Rate</Text>
              <Text style={{ 
                width: '7%', 
                padding: 4, 
                textAlign: 'center', 
                borderRight: '1pt solid #000' 
              }}>Unit</Text>
              <Text style={{ 
                width: '25%', 
                padding: 4, 
                textAlign: 'center' 
              }}>Amount</Text>
            </View>
            
            {/* Table Body */}
            {pdfItems.map((item, index) => (
              <View key={index} style={{ 
                flexDirection: 'row', 
                borderBottom: '1pt solid #000' 
              }}>
                <Text style={{ 
                  width: '6%', 
                  padding: 4, 
                  textAlign: 'center', 
                  borderRight: '1pt solid #000' 
                }}>{item.srNo}</Text>
                <Text style={{ 
                  width: '32%', 
                  padding: 4, 
                  borderRight: '1pt solid #000' 
                }}>{item.description}</Text>
                <Text style={{ 
                  width: '10%', 
                  padding: 4, 
                  textAlign: 'center', 
                  borderRight: '1pt solid #000' 
                }}>{item.itemNo}</Text>
                <Text style={{ 
                  width: '9%', 
                  padding: 4, 
                  textAlign: 'right', 
                  borderRight: '1pt solid #000' 
                }}>{parseFloat(item.quantity).toFixed(2)}</Text>
                <Text style={{ 
                  width: '11%', 
                  padding: 4, 
                  textAlign: 'right', 
                  borderRight: '1pt solid #000' 
                }}>{parseFloat(item.rate).toFixed(2)}</Text>
                <Text style={{ 
                  width: '7%', 
                  padding: 4, 
                  textAlign: 'center', 
                  borderRight: '1pt solid #000' 
                }}>{item.unit}</Text>
                <Text style={{ 
                  width: '25%', 
                  padding: 4, 
                  textAlign: 'right' 
                }}>{formatCurrency(item.amount)}</Text>
              </View>
            ))}
            
            {/* Table Footer */}
            <View style={{ 
              flexDirection: 'row', 
              backgroundColor: '#f9fafb', 
              borderBottom: '1pt solid #000' 
            }}>
              <Text style={{ 
                width: '75%', 
                padding: 4, 
                textAlign: 'right',
                 fontWeight: 'bold',  
                borderRight: '1pt solid #000' 
              }}>Total (A):</Text>
              <Text style={{ 
                width: '25%', 
                padding: 4, 
                textAlign: 'right' ,
                 fontWeight: 'bold', 
              }}>{formatCurrency(totals.itemsTotal)}</Text>
            </View>
            
            {/* Auxiliary Works (B) Title Row and Items - Only show if there are auxiliary works */}
            {totals.processedAuxWorks.length > 0 && (
              <>
                <View style={{ 
                  flexDirection: 'row', 
                  backgroundColor: '#f0f9ff', 
                  borderBottom: '1pt solid #000' 
                }}>
                  <Text style={{ 
                    width: '75%', 
                    padding: 6, 
                    textAlign: 'right', 
                    borderRight: '1pt solid #000',
                    fontWeight: 'bold',
                    fontSize: 11
                  }}>Auxiliary Works (B)</Text>
                  <Text style={{ 
                    width: '25%', 
                    padding: 6, 
                    textAlign: 'right',
                    fontWeight: 'bold',
                    fontSize: 11
                  }}></Text>
                </View>
                
                {/* Auxiliary Works Items */}
                {totals.processedAuxWorks.map((aux, index) => (
                  <View key={index} style={{ 
                    flexDirection: 'row', 
                    backgroundColor: '#f9fafb', 
                    borderBottom: '1pt solid #000' 
                  }}>
                    <Text style={{ 
                      width: '75%', 
                      padding: 4, 
                      textAlign: 'right', 
                      borderRight: '1pt solid #000' 
                    }}>
                      {aux.description}{aux.isPercentage ? ` (${formatPercentage(aux.percentage)}%)` : ' (Fixed Amount)'}:
                    </Text>
                    <Text style={{ 
                      width: '25%', 
                      padding: 4, 
                      textAlign: 'right' 
                    }}>{formatCurrency(aux.amount)}</Text>
                  </View>
                ))}
              </>
            )}
            
            <View style={{ 
              flexDirection: 'row', 
              backgroundColor: '#f9fafb', 
              borderBottom: '1pt solid #000' 
            }}>
              <Text style={{ 
                width: '75%', 
                padding: 4, 
                textAlign: 'right',
                 fontWeight: 'bold',  
                borderRight: '1pt solid #000' 
              }}>Total(A+B):</Text>
              <Text style={{ 
                width: '25%', 
                padding: 4, 
                textAlign: 'right', 
                 fontWeight: 'bold', 
              }}>{formatCurrency(totals.subtotal)}</Text>
            </View>
            
            <View style={{ 
              flexDirection: 'row', 
              backgroundColor: '#f9fafb', 
              borderBottom: '1pt solid #000' 
            }}>
              <Text style={{ 
                width: '75%', 
                padding: 4, 
                textAlign: 'right', 
                borderRight: '1pt solid #000' 
              }}>GST ({gstPercentage}%):</Text>
              <Text style={{ 
                width: '25%', 
                padding: 4, 
                textAlign: 'right' 
              }}>{formatCurrency(totals.gstAmount)}</Text>
            </View>
            
            <View style={{ 
              flexDirection: 'row', 
              backgroundColor: '#e5e7eb' 
            }}>
              <Text style={{ 
                width: '75%', 
                padding: 6, 
                textAlign: 'right', 
                borderRight: '1pt solid #000', 
                fontWeight: 'bold', 
                fontSize: 12 
              }}>Grand Total:</Text>
              <Text style={{ 
                width: '25%', 
                padding: 6, 
                textAlign: 'right', 
                fontWeight: 'bold', 
                fontSize: 12,
                flexWrap: 'nowrap'
              }}>{formatCurrency(totals.grandTotal)}</Text>
            </View>
          </View>
          
          {/* Fixed signature section with proper centering */}
          <View style={{ 
            flexDirection: 'row', 
            justifyContent: 'space-between', 
            marginTop: 50,
            paddingHorizontal: 40
          }}>
            <View style={{ 
              alignItems: 'center',
              width: 200
            }}>
              <View style={{ 
                borderBottom: '1pt solid #000', 
                height: 50, 
                width: 150,
                marginBottom: 8 
              }}></View>
              <Text style={{ 
                fontWeight: 'bold', 
                fontSize: 10,
                textAlign: 'center'
              }}>Prepared By</Text>
              {signatures.preparedBy && (
                <Text style={{ 
                  fontSize: 9,
                  textAlign: 'center',
                  marginTop: 3
                }}>{signatures.preparedBy}</Text>
              )}
            </View>
            
            <View style={{ 
              alignItems: 'center',
              width: 200
            }}>
              <View style={{ 
                borderBottom: '1pt solid #000', 
                height: 50, 
                width: 150,
                marginBottom: 8 
              }}></View>
              <Text style={{ 
                fontWeight: 'bold', 
                fontSize: 10,
                textAlign: 'center'
              }}>Checked By</Text>
              {signatures.checkedBy && (
                <Text style={{ 
                  fontSize: 9,
                  textAlign: 'center',
                  marginTop: 3
                }}>{signatures.checkedBy}</Text>
              )}
            </View>
          </View>
        </Page>
      </Document>
    );
    
    return await pdf(<AbstractDocument />).toBlob();
    
  } catch (err) {
    console.error("Error generating Abstract PDF:", err);
    throw err;
  }
};
const BufferPolyfill = {
  isBuffer: (obj) => {
    return obj instanceof Uint8Array || 
           (obj && typeof obj === 'object' && obj.constructor === Uint8Array) ||
           (obj && typeof obj === 'object' && obj.type === 'Buffer');
  },
  
  from: (data, encoding) => {
    if (typeof data === 'string') {
      if (encoding === 'base64') {
        try {
          const binaryString = atob(data);
          const bytes = new Uint8Array(binaryString.length);
          for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
          }
          return bytes;
        } catch (error) {
          console.error('Error decoding base64:', error);
          return new Uint8Array(0);
        }
      }
      // For other encodings, convert string to Uint8Array
      const encoder = new TextEncoder();
      return encoder.encode(data);
    }
    
    if (data instanceof ArrayBuffer) {
      return new Uint8Array(data);
    }
    
    if (data instanceof Uint8Array) {
      return data;
    }
    
    if (Array.isArray(data)) {
      return new Uint8Array(data);
    }
    
    return new Uint8Array(0);
  },
  
  alloc: (size, fill = 0) => {
    const buffer = new Uint8Array(size);
    if (fill !== 0) {
      buffer.fill(fill);
    }
    return buffer;
  },
  
  concat: (buffers, totalLength) => {
    if (!Array.isArray(buffers)) {
      throw new TypeError('First argument must be an array');
    }
    
    if (buffers.length === 0) {
      return new Uint8Array(0);
    }
    
    let length = totalLength;
    if (length === undefined) {
      length = buffers.reduce((acc, buf) => acc + buf.length, 0);
    }
    
    const result = new Uint8Array(length);
    let offset = 0;
    
    for (const buf of buffers) {
      if (offset + buf.length > length) {
        result.set(buf.slice(0, length - offset), offset);
        break;
      }
      result.set(buf, offset);
      offset += buf.length;
    }
    
    return result;
  }
};

// Set global Buffer if not available
if (typeof Buffer === 'undefined') {
  window.Buffer = BufferPolyfill;
}

// Also add isBuffer as a standalone function
if (typeof window !== 'undefined' && !window.Buffer) {
  window.Buffer = BufferPolyfill;
}
// Fixed processImageData function
const processImageData = (imageData) => {
  if (!imageData || typeof imageData !== 'string') {
    return null;
  }
  
  try {
    // Check if it's a valid data URL
    if (imageData.startsWith('data:image/')) {
      // Validate the base64 part
      const base64Part = imageData.split('base64,')[1];
      if (base64Part) {
        // Test if base64 is valid
        atob(base64Part);
        return imageData;
      }
    }
    
    // If it's base64 without data URL prefix, add it
    if (imageData.match(/^[A-Za-z0-9+/=]+$/)) {
      // Test if base64 is valid
      atob(imageData);
      return `data:image/png;base64,${imageData}`;
    }
  } catch (error) {
    console.warn('Invalid image data:', error);
  }
  
  return null;
};


// 6. Function to merge PDFs
const mergePDFs = async (pdfBlobs) => {
  try {
    console.log(`Merging ${pdfBlobs.length} PDF(s)...`);
    
    // Validate input
    if (!Array.isArray(pdfBlobs) || pdfBlobs.length === 0) {
      throw new Error('No PDFs provided for merging');
    }
    
    // If only one PDF, return it as-is
    if (pdfBlobs.length === 1) {
      return pdfBlobs[0];
    }
    
    const mergedPdf = await PDFDocument.create();
    
    for (let i = 0; i < pdfBlobs.length; i++) {
      const blob = pdfBlobs[i];
      console.log(`Processing PDF ${i + 1}/${pdfBlobs.length} (${blob.size} bytes)`);
      
      try {
        const arrayBuffer = await blob.arrayBuffer();
        const pdf = await PDFDocument.load(arrayBuffer);
        const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
        copiedPages.forEach((page) => mergedPdf.addPage(page));
        console.log(`Added ${copiedPages.length} pages from PDF ${i + 1}`);
      } catch (pdfError) {
        console.error(`Error processing PDF ${i + 1}:`, pdfError);
        throw new Error(`Failed to process PDF ${i + 1}: ${pdfError.message}`);
      }
    }
    
    const pdfBytes = await mergedPdf.save();
    const finalBlob = new Blob([pdfBytes], { type: 'application/pdf' });
    console.log(`Merged PDF created (${finalBlob.size} bytes)`);
    
    return finalBlob;
  } catch (error) {
    console.error('Error merging PDFs:', error);
    throw new Error(`PDF merge failed: ${error.message}`);
  }
};


// Add the handlePrevStep function
const handlePrevStep = (step) => {
  setCurrentStep(step);
  toast.info("Going back to previous step");
};

 const fetchMeasurements = async (itemId) => {
    try {
      const res = await fetch(`${API_BASE_URL}/txn-items-mts/ByItemId/${itemId}`, {
        headers: { Authorization: `Bearer ${jwtToken}` }
      });
      
      if (!res.ok) {
        throw new Error(`Failed to fetch measurements. Status: ${res.status}`);
      }
      
      return await res.json();
    } catch (err) {
      console.error(`Error fetching measurements for item ${itemId}:`, err);
      return [];
    }
  };
 
  const fetchItems = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const subRecordCache = localStorage.getItem('subRecordCache');
      
      if (!subRecordCache) {
        setError("No measurement data found in local storage");
        setLoading(false);
        return;
      }
      
      let parsedItems;
      try {
        const itemsObject = JSON.parse(subRecordCache);
        
        if (Array.isArray(itemsObject)) {
          parsedItems = itemsObject;
        } else if (typeof itemsObject === 'object') {
          parsedItems = Object.values(itemsObject).flat();
        } else {
          throw new Error("Invalid data format in subRecordCache");
        }
      } catch (parseErr) {
        console.error("Error parsing subRecordCache:", parseErr);
        setError("Invalid measurement data format in local storage");
        setLoading(false);
        return;
      }
      
      const detailedItems = await Promise.all(
        parsedItems.map(async (item) => {
          if (item.measurements && Array.isArray(item.measurements)) {
            return item;
          }
          const measurements = await fetchMeasurements(item.id);
          return { ...item, measurements };
        })
      );
      
      setItems(detailedItems);
    } catch (err) {
      console.error("Error fetching item details:", err);
      setError("Failed to load measurement data");
    } finally {
      setLoading(false);
    }
  };


  const handleComponentToggle = (component) => {
    setSelectedComponents(prev => ({
      ...prev,
      [component]: !prev[component]
    }));
  };


  const ensureCoverPageData = async () => {
  try {
    const savedCoverPageData = localStorage.getItem('coverPageData');
    if (savedCoverPageData) {
      const coverPageData = JSON.parse(savedCoverPageData);
      
      if (coverPageData.estimateCost && coverPageData.workName) {
        console.log("Using saved cover page data:", coverPageData);
        
        // Handle company logo if it's base64
        let processedLogo = coverPageData.companyLogo;
        if (processedLogo && typeof processedLogo === 'string' && processedLogo.startsWith('data:')) {
          try {
            // Keep as base64 string for React PDF
            processedLogo = coverPageData.companyLogo;
          } catch (logoError) {
            console.warn('Error processing logo:', logoError);
            processedLogo = null;
          }
        }
        
        const constructionEstimateData = {
          grandTotal: parseFloat(coverPageData.estimateCost) || 0,
          workOrderId: workInfo.workOrderId,
          workName: coverPageData.workName,
          area: workInfo.area || '900',
          ssr: coverPageData.year || workInfo.ssr || '',
          items: items.length,
          revisionNumber: workInfo.revisionNumber,
          coverPageData: {
            ...coverPageData,
            companyLogo: processedLogo
          }
        };
        
        setConstructionEstimate(constructionEstimateData);
        localStorage.setItem("constructionEstimate", JSON.stringify(constructionEstimateData));
        
        localStorage.setItem("abstractWorkName", coverPageData.workName);
        localStorage.setItem("abstractWorkOrderId", workInfo.workOrderId);
        localStorage.setItem("abstractArea", workInfo.area || "900");
        localStorage.setItem("abstractSSR", coverPageData.year || workInfo.ssr || "");
        
        return constructionEstimateData;
      }
    }
    
    if (constructionEstimate && constructionEstimate.grandTotal !== undefined) {
      return constructionEstimate;
    }
    
    let grandTotal = 0;
    
    for (const item of items) {
      const quantity = Array.isArray(item.measurements) 
        ? item.measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0) 
        : 0;
      
      const amount = quantity * (parseFloat(item.labourRate) || 0);
      grandTotal += amount;
    }
    
    const newConstructionEstimate = {
      grandTotal: grandTotal || 0,
      workOrderId: workInfo.workOrderId,
      workName: workInfo.nameOfWork,
      area: workInfo.area || '900',
      ssr: workInfo.ssr || '',
      items: items.length,
      revisionNumber: workInfo.revisionNumber
    };
    
    setConstructionEstimate(newConstructionEstimate);
    localStorage.setItem("constructionEstimate", JSON.stringify(newConstructionEstimate));
    
    localStorage.setItem("abstractWorkName", workInfo.nameOfWork);
    localStorage.setItem("abstractWorkOrderId", workInfo.workOrderId);
    localStorage.setItem("abstractArea", workInfo.area || "900");
    localStorage.setItem("abstractSSR", workInfo.ssr || "");
    
    return newConstructionEstimate;
  } catch (error) {
    console.error("Error ensuring cover page data:", error);
    throw new Error(`Failed to prepare cover page data: ${error.message}`);
  }
};const generateCombinedPDF = async () => {
  let loadingToast;
  
  try {
    // Validate selections
    if (!selectedComponents.abstract && !selectedComponents.coverPage) {
      toast.error("Please select at least one component to include in the PDF");
      return;
    }

    // Validate required data
    if (!workInfo || !workInfo.workOrderId) {
      toast.error("Missing work order information");
      return;
    }

    const { nameOfWork, workOrderId, revisionNumber } = workInfo;
    loadingToast = toast.loading('Generating PDF...');
    
    console.log('Starting PDF generation...', {
      abstract: selectedComponents.abstract,
      coverPage: selectedComponents.coverPage,
      workOrderId,
      revisionNumber
    });

    let finalBlob;
    // Use exact naming format: workOrderId_revisionNumber.pdf
    let fileName = `${workOrderId}_${revisionNumber || '1'}.pdf`;
    const pdfBlobs = [];

    try {
      // Generate cover page first if selected
      if (selectedComponents.coverPage) {
        console.log('Generating cover page PDF...');
        try {
          const coverPageBlob = await generateCoverPageBlob();
          if (coverPageBlob && coverPageBlob.size > 0) {
            pdfBlobs.push(coverPageBlob);
            console.log(`Cover page generated (${coverPageBlob.size} bytes)`);
          } else {
            throw new Error('Cover page blob is empty');
          }
        } catch (coverError) {
          console.error('Cover page generation failed:', coverError);
          // Try fallback simple cover page
          try {
            const simpleCoverBlob = await generateSimpleCoverPageBlob();
            if (simpleCoverBlob && simpleCoverBlob.size > 0) {
              pdfBlobs.push(simpleCoverBlob);
              console.log(`Simple cover page generated (${simpleCoverBlob.size} bytes)`);
            }
          } catch (simpleCoverError) {
            console.error('Simple cover page also failed:', simpleCoverError);
            toast.warning('Cover page generation failed, skipping...');
          }
        }
      }

      // Generate abstract if selected
      if (selectedComponents.abstract) {
        console.log('Generating abstract PDF...');
        try {
          const abstractBlob = await generateAbstractPDFBlob();
          if (abstractBlob && abstractBlob.size > 0) {
            pdfBlobs.push(abstractBlob);
            console.log(`Abstract generated (${abstractBlob.size} bytes)`);
          } else {
            throw new Error('Abstract blob is empty');
          }
        } catch (abstractError) {
          console.error('Abstract generation failed:', abstractError);
          toast.error(`Abstract generation failed: ${abstractError.message}`);
          throw abstractError;
        }
      }

      // Check if we have any PDFs to work with
      if (pdfBlobs.length === 0) {
        throw new Error('No PDF components were successfully generated');
      }

      // Merge or use single PDF
      if (pdfBlobs.length > 1) {
        console.log('Merging PDFs...');
        finalBlob = await mergePDFs(pdfBlobs);
      } else {
        finalBlob = pdfBlobs[0];
      }

      // Validate final blob
      if (!finalBlob || finalBlob.size === 0) {
        throw new Error('Generated PDF is empty');
      }

      toast.dismiss(loadingToast);
      console.log(`PDF generated successfully (${finalBlob.size} bytes), attempting upload...`);

      // Try to upload to server
      try {
        const uploadResult = await uploadPDFToServer(finalBlob, fileName);
        console.log('PDF uploaded successfully:', uploadResult);
      } catch (uploadError) {
        console.error("Upload failed:", uploadError);
        // The uploadPDFToServer function already handles fallback download
        throw uploadError;
      }

    } catch (generationError) {
      toast.dismiss(loadingToast);
      console.error("PDF generation error:", generationError);
      toast.error(`Failed to generate PDF: ${generationError.message}`);
      throw generationError;
    }
    
  } catch (error) {
    if (loadingToast) {
      toast.dismiss(loadingToast);
    }
    console.error("Error in generateCombinedPDF:", error);
    
    // Provide more specific error messages
    if (error.message.includes('Buffer.isBuffer')) {
      toast.error('PDF generation failed due to browser compatibility. Please try refreshing the page.');
    } else if (error.message.includes('network') || error.message.includes('fetch')) {
      toast.error('Network error during PDF upload. Please check your connection.');
    } else {
      toast.error(`PDF generation failed: ${error.message}`);
    }
  }
};
const generateSimpleCoverPageBlob = async () => {
  try {
    const { nameOfWork, workOrderId, revisionNumber } = workInfo;
    
    const SimpleDocument = () => (
      <Document>
        <Page size="A4" style={{ padding: 40, fontFamily: 'Helvetica' }}>
          <View style={{ textAlign: 'center', marginTop: 100 }}>
            <Text style={{ fontSize: 24, fontWeight: 'bold', marginBottom: 30 }}>
              ESTIMATE COVER PAGE
            </Text>
            <Text style={{ fontSize: 16, marginBottom: 15 }}>
              Work: {nameOfWork || 'Work Name Not Available'}
            </Text>
            <Text style={{ fontSize: 14, marginBottom: 10 }}>
              Work Order ID: {workOrderId || 'WO-001'}
            </Text>
            <Text style={{ fontSize: 14, marginBottom: 10 }}>
              Revision: {revisionNumber || '1'}
            </Text>
            <Text style={{ fontSize: 14 }}>
              Date: {new Date().toLocaleDateString('en-IN')}
            </Text>
          </View>
        </Page>
      </Document>
    );
    
    return await pdf(<SimpleDocument />).toBlob();
  } catch (error) {
    console.error('Simple cover page generation failed:', error);
    throw error;
  }
};

// 8. Helper function to generate cover page blob
// Fixed generateCoverPageBlob function with better image handling
const generateCoverPageBlob = async () => {
  try {
    const savedCoverPageData = localStorage.getItem('coverPageData');
    let coverPageData = {};
    
    if (savedCoverPageData) {
      try {
        coverPageData = JSON.parse(savedCoverPageData);
      } catch (parseError) {
        console.error("Error parsing cover page data:", parseError);
        coverPageData = {};
      }
    }

    let estimateCost = 0;
    if (coverPageData.estimateCost) {
      estimateCost = parseFloat(coverPageData.estimateCost) || 0;
    } else if (constructionEstimate && constructionEstimate.grandTotal) {
      estimateCost = constructionEstimate.grandTotal;
    } else {
      for (const item of items) {
        const quantity = Array.isArray(item.measurements) 
          ? item.measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0) 
          : 0;
        const amount = quantity * (parseFloat(item.labourRate) || 0);
        estimateCost += amount;
      }
    }

    // Safely process company logo
    let processedLogo = null;
    if (coverPageData.companyLogo && typeof coverPageData.companyLogo === 'string') {
      try {
        // Validate that it's a proper data URL
        if (coverPageData.companyLogo.startsWith('data:image/') && 
            coverPageData.companyLogo.includes('base64,')) {
          // Additional validation - check if base64 data is valid
          const base64Data = coverPageData.companyLogo.split('base64,')[1];
          if (base64Data && base64Data.length > 0) {
            // Test if base64 data is valid by trying to decode it
            try {
              atob(base64Data);
              processedLogo = coverPageData.companyLogo;
            } catch (base64Error) {
              console.warn("Invalid base64 image data, skipping logo");
              processedLogo = null;
            }
          }
        }
      } catch (logoError) {
        console.warn("Error processing company logo:", logoError);
        processedLogo = null;
      }
    }

    const coverPageProps = {
      companyLogo: processedLogo,
      companyName: String(coverPageData.companyName || 'Company Name Not Set'),
      companyAddress: String(coverPageData.address || coverPageData.companyAddress || 'Address Not Set'),
      workName: String(coverPageData.workName || workInfo.nameOfWork || 'Work Name Not Set'),
      workOrderId: String(workInfo.workOrderId || 'WO-001'),
      revisionNumber: String(workInfo.revisionNumber || '1'),
      clientName: String(coverPageData.clientName || 'Client Name Not Set'),
      propertyNo: String(coverPageData.propertyNo || 'Property No Not Set'),
      propertyAddress: String(coverPageData.propertyAddress || 'Property Address Not Set'),
      estimateCost: estimateCost,
      sorYear: String(coverPageData.year || coverPageData.sorYear || new Date().getFullYear()),
      area: String(workInfo.area || coverPageData.area || '900'),
      ssr: String(coverPageData.year || coverPageData.ssr || workInfo.ssr || '')
    };

    // Create a simplified cover page component to avoid image issues
    const SimpleCoverPagePDF = ({ 
      companyName, 
      companyAddress, 
      workName, 
      workOrderId, 
      revisionNumber, 
      clientName, 
      propertyNo, 
      propertyAddress, 
      estimateCost, 
      sorYear, 
      area, 
      ssr 
    }) => (
      <Page size="A4" style={{ padding: 40, fontFamily: 'Helvetica' }}>
        {/* Header Section */}
        <View style={{ textAlign: 'center', marginBottom: 30 }}>
          <Text style={{ fontSize: 20, fontWeight: 'bold', marginBottom: 10 }}>
            {companyName}
          </Text>
          <Text style={{ fontSize: 12, marginBottom: 20 }}>
            {companyAddress}
          </Text>
          <Text style={{ fontSize: 16, fontWeight: 'bold', textDecoration: 'underline' }}>
            ESTIMATE COVER PAGE
          </Text>
        </View>

        {/* Work Details Section */}
        <View style={{ marginBottom: 30 }}>
          <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 15 }}>
            WORK DETAILS
          </Text>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Work Name:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{workName}</Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Work Order ID:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{workOrderId}</Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Revision Number:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{revisionNumber}</Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Area:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{area} sq ft</Text>
          </View>
          
          {ssr && (
            <View style={{ flexDirection: 'row', marginBottom: 8 }}>
              <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>SSR:</Text>
              <Text style={{ width: '70%', fontSize: 12 }}>{ssr}</Text>
            </View>
          )}
        </View>

        {/* Client Details Section */}
        <View style={{ marginBottom: 30 }}>
          <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 15 }}>
            CLIENT DETAILS
          </Text>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Client Name:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{clientName}</Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Property No:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{propertyNo}</Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Property Address:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{propertyAddress}</Text>
          </View>
        </View>

        {/* Estimate Details Section */}
        <View style={{ marginBottom: 30 }}>
          <Text style={{ fontSize: 14, fontWeight: 'bold', marginBottom: 15 }}>
            ESTIMATE DETAILS
          </Text>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>SOR Year:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>{sorYear}</Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Estimate Cost:</Text>
            <Text style={{ width: '70%', fontSize: 12, fontWeight: 'bold' }}>
              {estimateCost.toLocaleString('en-IN', { 
                style: 'currency', 
                currency: 'INR', 
                minimumFractionDigits: 2 
              })}
            </Text>
          </View>
          
          <View style={{ flexDirection: 'row', marginBottom: 8 }}>
            <Text style={{ width: '30%', fontSize: 12, fontWeight: 'bold' }}>Date:</Text>
            <Text style={{ width: '70%', fontSize: 12 }}>
              {new Date().toLocaleDateString('en-IN')}
            </Text>
          </View>
        </View>

        {/* Footer */}
        <View style={{ 
          position: 'absolute', 
          bottom: 40, 
          left: 40, 
          right: 40, 
          textAlign: 'center' 
        }}>
          <Text style={{ fontSize: 10, color: '#666' }}>
            This estimate is prepared based on current market rates and is subject to change.
          </Text>
        </View>
      </Page>
    );

    // Try to use the full CoverPagePDF component first, fallback to simple version
    let CoverPageDocument;
    
    if (processedLogo && typeof CoverPagePDF === 'function') {
      // If logo is valid and CoverPagePDF component exists, try to use it
      try {
        CoverPageDocument = () => (
          <Document>
            <CoverPagePDF {...coverPageProps} />
          </Document>
        );
        
        // Test render to see if it works
        const testBlob = await pdf(<CoverPageDocument />).toBlob();
        if (testBlob) {
          return testBlob;
        }
      } catch (error) {
        console.warn("CoverPagePDF component failed, using simple version:", error);
      }
    }
    
    // Fallback to simple cover page
    CoverPageDocument = () => (
      <Document>
        <SimpleCoverPagePDF {...coverPageProps} />
      </Document>
    );
    
    return await pdf(<CoverPageDocument />).toBlob();
    
  } catch (error) {
    console.error("Error generating cover page:", error);
    
    // Ultimate fallback - create a very basic cover page
    const BasicCoverPageDocument = () => (
      <Document>
        <Page size="A4" style={{ padding: 40, fontFamily: 'Helvetica' }}>
          <View style={{ textAlign: 'center', marginTop: 100 }}>
            <Text style={{ fontSize: 24, fontWeight: 'bold', marginBottom: 20 }}>
              ESTIMATE COVER PAGE
            </Text>
            <Text style={{ fontSize: 16, marginBottom: 10 }}>
              Work: {workInfo.nameOfWork || 'Work Name Not Set'}
            </Text>
            <Text style={{ fontSize: 14, marginBottom: 10 }}>
              Work Order ID: {workInfo.workOrderId || 'WO-001'}
            </Text>
            <Text style={{ fontSize: 14, marginBottom: 10 }}>
              Revision: {workInfo.revisionNumber || '1'}
            </Text>
            <Text style={{ fontSize: 14 }}>
              Date: {new Date().toLocaleDateString('en-IN')}
            </Text>
          </View>
        </Page>
      </Document>
    );
    
    return await pdf(<BasicCoverPageDocument />).toBlob();
  }
};
const handleStepperClick = (stepId) => {
  if (stepId < currentStep) {
    setCurrentStep(stepId); // Go back freely
  } else {
    handleNextStep(stepId); // Apply forward step validation
  }
};

  const prepareAbstractData = async () => {
    try {
      let itemsToProcess = [];
      
      if (Array.isArray(items)) {
        itemsToProcess = items;
      } else if (typeof items === 'object' && items !== null) {
        const allSubworkIds = Object.keys(items);
        
        if (allSubworkIds.length === 0) {
          throw new Error("No subworks or items found to generate abstract");
        }
        
        itemsToProcess = allSubworkIds.flatMap(subworkId => items[subworkId] || []);
      }
      
      if (itemsToProcess.length === 0) {
        throw new Error("No items found to generate abstract");
      }
      
      const processedItems = await Promise.all(
        itemsToProcess.map(async (item) => {
          let measurements = item.measurements;
          
          if (!measurements || !Array.isArray(measurements)) {
            try {
              measurements = await fetchMeasurements(item.id);
            } catch (err) {
              console.error(`Error fetching measurements for item ${item.id}:`, err);
              measurements = [];
            }
          }
          
          const quantity = Array.isArray(measurements) 
            ? measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0) 
            : 0;
          
          // Ensure all required fields are present with safe defaults
          return { 
            ...item, 
            id: item.id || Math.random().toString(36).substr(2, 9),
            itemNo: item.itemNo || item.itemNumber || 'N/A',
            descriptionOfItem: item.descriptionOfItem || item.description || 'No description',
            unit: item.unit || 'Nos',
            labourRate: item.labourRate || item.rate || 0,
            measurements: Array.isArray(measurements) ? measurements : [],
            quantity: quantity,
            amount: quantity * (parseFloat(item.labourRate || item.rate) || 0)
          };
        })
      );
      
      setAbstractItems(processedItems);
      localStorage.setItem("abstractItems", JSON.stringify(processedItems));
      
      localStorage.setItem("abstractWorkName", workInfo.nameOfWork);
      localStorage.setItem("abstractWorkOrderId", workInfo.workOrderId);
      localStorage.setItem("abstractArea", workInfo.area || "900");
      localStorage.setItem("abstractSSR", workInfo.ssr || "");
      
      return processedItems;
    } catch (error) {
      console.error("Error preparing abstract data:", error);
      throw error;
    }
  };

  // Auto-prepare data when components are selected
  useEffect(() => {
    if (items.length > 0) {
      if (selectedComponents.abstract && abstractItems.length === 0) {
        prepareAbstractData().catch(console.error);
      }
      
      if (selectedComponents.coverPage && !constructionEstimate) {
        ensureCoverPageData().catch(console.error);
      }
    }
  }, [selectedComponents, items]);

  const renderBankEstimateContent = () => {
    if (loading) {
      return (
        <div className="text-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading measurement data...</p>
        </div>
      );
    }

    if (error) {
      return (
        
        <div className="text-center py-8">
          
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 max-w-md mx-auto">
            <div className="text-red-600 mb-4">
              <X className="mx-auto mb-2" size={32} />
              <p className="font-medium">{error}</p>
            </div>
            <button 
              onClick={fetchItems} 
              className="bg-red-600 text-white px-6 py-2 rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      );
    }

    return (
      <div className="space-y-8">
        {/* Component Selection Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Cover Page Card */}
          <div 
            className={`group relative overflow-hidden rounded-xl border-2 transition-all duration-300 cursor-pointer ${
              selectedComponents.coverPage 
                ? 'border-blue-500 bg-blue-50 shadow-lg' 
                : 'border-gray-200 bg-white hover:border-blue-300 hover:shadow-md'
            }`}
            onClick={() => handleComponentToggle('coverPage')}
          >
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className={`p-3 rounded-lg ${selectedComponents.coverPage ? 'bg-blue-500' : 'bg-gray-100'}`}>
                    <FileCheck className={`${selectedComponents.coverPage ? 'text-white' : 'text-gray-600'}`} size={24} />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">Cover Page</h3>
                    <p className="text-sm text-gray-500">Project overview & details</p>
                  </div>
                </div>
                <div className={`w-6 h-6 rounded-full flex items-center justify-center transition-colors ${
                  selectedComponents.coverPage ? 'bg-blue-500' : 'bg-gray-300'
                }`}>
                  {selectedComponents.coverPage && <Check size={16} className="text-white" />}
                </div>
              </div>
              <div className="text-sm text-gray-600">
                <span className="flex items-center space-x-1">
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Company information</span>
                  <span className="text-gray-400">•</span>
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Project details</span>
                  <span className="text-gray-400">•</span>
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Cost estimate</span>
                </span>
              </div>
            </div>
            {selectedComponents.coverPage && (
              <div className="absolute top-2 right-2">
                <div className="bg-blue-500 text-white text-xs px-2 py-1 rounded-full">
                  Selected
                </div>
              </div>
            )}
          </div>

          {/* Abstract Card */}
          <div 
            className={`group relative overflow-hidden rounded-xl border-2 transition-all duration-300 cursor-pointer ${
              selectedComponents.abstract 
                ? 'border-blue-500 bg-purple-50 shadow-lg' 
                : 'border-gray-200 bg-white hover:border-purple-300 hover:shadow-md'
            }`}
            onClick={() => handleComponentToggle('abstract')}
          >
            <div className="p-6">
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className={`p-3 rounded-lg ${selectedComponents.abstract ? 'bg-blue-500' : 'bg-gray-100'}`}>
                    <FileText className={`${selectedComponents.abstract ? 'text-white' : 'text-gray-600'}`} size={24} />
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900">Abstract</h3>
                    <p className="text-sm text-gray-500">Cost breakdown summary</p>
                  </div>
                </div>
                <div className={`w-6 h-6 rounded-full flex items-center justify-center transition-colors ${
                  selectedComponents.abstract ? 'bg-blue-500' : 'bg-gray-300'
                }`}>
                  {selectedComponents.abstract && <Check size={16} className="text-white" />}
                </div>
              </div>
              <div className="text-sm text-gray-600">
                <span className="flex items-center space-x-1">
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Item-wise costs</span>
                  <span className="text-gray-400">•</span>
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Quantity analysis</span>
                  <span className="text-gray-400">•</span>
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span>Total estimation</span>
                </span>
              </div>
            </div>
            {selectedComponents.abstract && (
              <div className="absolute top-2 right-2">
                <div className="bg-blue-500 text-white text-xs px-2 py-1 rounded-full">
                  Selected
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Preview Sections */}
        <div className="space-y-6">
          {selectedComponents.coverPage && (
            <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-xl border border-blue-200 overflow-hidden">
              <div className="bg-white border-b border-blue-200 p-4">
                <div className="flex items-center space-x-2">
                  <Eye className="text-blue-600" size={20} />
                  <h3 className="font-semibold text-gray-800">Cover Page Preview</h3>
                </div>
              </div>
              <div className="p-6">
                <CoverPageGenerator />
              </div>
            </div>
          )}

          {selectedComponents.abstract && (
            <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-xl border border-purple-200 overflow-hidden">
              <div className="bg-white border-b border-purple-200 p-4">
                <div className="flex items-center space-x-2">
                  <Eye className="text-blue-600" size={20} />
                  <h3 className="font-semibold text-gray-800">Abstract Preview</h3>
                </div>
              </div>
              <div className="p-6">
                <ConstructionEstimateComponent />
              </div>
            </div>
          )}
        </div>

        {/* Action Button */}
        <div className="flex justify-center pt-6">
          <button 
            onClick={generateCombinedPDF}
            className="group relative bg-gradient-to-r from-blue-600 to-indigo-600 text-white py-4 px-8 rounded-xl hover:from-blue-700 hover:to-indigo-700 transition-all duration-300 flex items-center justify-center text-base shadow-lg hover:shadow-xl transform hover:-translate-y-1"
            disabled={loading || (!selectedComponents.coverPage && !selectedComponents.abstract)}
          >
            <Download className="mr-3 group-hover:animate-bounce" size={20} />
            <span className="font-semibold">Generate Bank Estimate PDF</span>
            <div className="absolute inset-0 rounded-xl bg-white opacity-0 group-hover:opacity-10 transition-opacity"></div>
          </button>
        </div>
      </div>
    );
  };

 const renderMTSContent = () => {
    if (loading) {
      return (
        <div className="text-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading measurement data...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="text-center py-8">
          <div className="bg-red-50 border border-red-200 rounded-lg p-6 max-w-md mx-auto">
            <div className="text-red-600 mb-4">
              <X className="mx-auto mb-2" size={32} />
              <p className="font-medium">{error}</p>
            </div>
            <button 
              onClick={fetchItems} 
              className="bg-red-600 text-white px-6 py-2 rounded-lg hover:bg-red-700 transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      );
    }

    if (!items || items.length === 0) {
      return (
        <div className="text-center py-12">
          <FileText className="mx-auto mb-4 text-gray-400" size={48} />
          <p className="text-gray-600 text-lg">No measurement data available</p>
        </div>
      );
    }
   
   const renderStepperSection = () => (
  <div className="mb-6">
    <div className="mb-6 mt-2 p-4 border border-gray-300 rounded bg-white shadow">
      <StepperPage 
        currentStep={currentStep}
        onStepClick={(stepId) => {
          if (stepId < currentStep) {
            handlePrevStep(stepId); // Go back freely
          } else {
            handleNextStep(stepId); // Apply forward step validation
          }
        }} 
      />
    </div>
  </div>
);
     return (
      <div className="space-y-6">
       
        <div className="mb-6">
        </div>
        
        <div className="bg-gradient-to-r from-indigo-50 to-blue-50 rounded-xl border border-indigo-200 overflow-hidden">
          <div className="bg-white border-b border-indigo-200 p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Eye className="text-indigo-600" size={20} />
                <h3 className="font-semibold text-gray-800">Measurement Sheet Preview</h3>
              </div>
              
            </div>
          </div>
          <div className="p-6">
            <div className="h-[600px] rounded-lg overflow-hidden border border-gray-300 bg-white shadow-inner">
             <PDFViewer 
  width="100%" 
  height="100%" 
  style={{ 
    border: 'none', 
    borderRadius: '8px',
    backgroundColor: '#ffffff'
  }}
  showToolbar={false}
>
  <Document>
    <MeasurementPDF 
      workOrderId={workInfo.workOrderId} 
      nameOfWork={workInfo.nameOfWork} 
      items={items} 
      signatures={signatures}
      showWatermark={true} // Add this prop for preview
    />
  </Document>
</PDFViewer>
            </div>
          </div>
        </div>
        <button 
                onClick={() => {
                  // 4. Replace the MTS PDF generation button onClick function with this:
const generateMTSPDF = async () => {
  try {
    const { nameOfWork, workOrderId, revisionNumber } = workInfo;
    const fileName = `${workOrderId || 'document'}_${revisionNumber || '1'}.pdf`;
    const loadingToast = toast.loading('Generating MTS PDF...');

    const MTSDocument = () => (
  <Document>
    <MeasurementPDF 
      workOrderId={workOrderId || 'WO-001'} 
      nameOfWork={nameOfWork || 'Construction Work'} 
      items={items}
      signatures={signatures}
      showWatermark={false} // Add this prop - no watermark for download
    />
  </Document>
);

    const blob = await pdf(<MTSDocument />).toBlob();
    
    toast.dismiss(loadingToast);
    
    // Upload PDF to server
    try {
      await uploadPDFToServer(blob, fileName);
    } catch (uploadError) {
      console.error("Upload failed, falling back to download:", uploadError);
      // Fallback to download if upload fails
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = fileName;
      link.click();
      URL.revokeObjectURL(link.href);
      toast.success('MTS PDF downloaded locally (upload failed)');
    }
  } catch (err) {
    console.error("Error generating MTS PDF:", err);
    toast.error(`Failed to generate MTS PDF: ${err.message}`);
  }
};

                  generateMTSPDF();
                }}
                className="group relative bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-2 px-4 rounded-lg hover:from-indigo-700 hover:to-purple-700 transition-all duration-300 flex items-center shadow-lg hover:shadow-xl"
                disabled={loading}
              >
                <Download className="mr-2 group-hover:animate-bounce" size={16} />
                <span className="font-medium">Download PDF</span>
              </button>
      </div>
      
    );
  };
return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          
       
           <div className="mb-4">
            <StepperPage 
              currentStep={currentStep} 
              onStepClick={handleStepperClick}
            />
          </div>
        </div>

        {/* Document Type Selector */}
        <div className="mb-8">
          <div className="bg-white rounded-xl shadow-lg p-6">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Select Document Type</h2>
            <div className="flex flex-wrap gap-4">
              {documentOptions.map((option) => {
                const IconComponent = option.icon;
                return (
                  <button
                    key={option.value}
                    onClick={() => setSelectedDocument(option.value)}
                    className={`flex items-center space-x-3 px-6 py-4 rounded-lg border-2 transition-all duration-300 ${
                      selectedDocument === option.value
                        ? 'border-blue-500 bg-blue-50 text-blue-700'
                        : 'border-gray-200 bg-white text-gray-700 hover:border-blue-300 hover:bg-blue-50'
                    }`}
                  >
                    <IconComponent size={24} />
                    <span className="font-medium">{option.label}</span>
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        {/* Content Area */}
        <div className="bg-white rounded-xl shadow-lg p-8">
          {selectedDocument === 'bankEstimate' ? renderBankEstimateContent() : renderMTSContent()}
        </div>

        
      </div>
    </div>
  );
};

export default BackEstimate;
