// PDFGenerator.js
import React, { useEffect, useState, useRef } from 'react';
import html2pdf from 'html2pdf.js';
import Stepper from './Stepper'; // Adjust the path if needed


const PDFGenerator = () => {
  const [items, setItems] = useState([]);
  const pdfRef = useRef(null);

  const token = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI5MjA5MTYwNjEyIiwiaWF0IjoxNzQzNTk5NzEwLCJleHAiOjE3NDM2ODYxMTB9.eE7zAbpk536w3O_kdm13YlP6_YRmIzmGtemC2GlWv60";
  const workOrderID = localStorage.getItem('autogenerated') || 'Measurement_Sheet';
  const revisionno = localStorage.getItem('reviseno') || 'Measurement_Sheet';
  const nameOfWork = localStorage.getItem('nameOfWork') || 'No Work Name Found';
  const subRecordCache = JSON.parse(localStorage.getItem('subRecordCache') || '{}');

  const fetchMeasurements = async (itemId) => {
    try {
      const res = await fetch(`http://24.101.103.87:8082/api/txn-items-mts/ByItemId/${itemId}`, {
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      return await res.json();
    } catch (err) {
      console.error("Error fetching MTS for item", itemId, err);
      return [];
    }
  };

  const fetchItems = async () => {
    let allItems = Object.values(subRecordCache).flat();
    const itemsWithMeasurements = await Promise.all(
      allItems.map(async item => {
        const measurements = await fetchMeasurements(item.id);
        return { ...item, measurements };
      })
    );
    setItems(itemsWithMeasurements);
  };

  useEffect(() => {
    fetchItems();
  }, []);

  const exportToPDF = () => {
    const element = pdfRef.current;
    const options = {
      filename: `${workOrderID}_${revisionno}.pdf`,
      image: { type: 'jpeg', quality: 1 },
      html2canvas: {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
        scrollY: 0,
        windowWidth: document.documentElement.scrollWidth,
      },
      jsPDF: {
        unit: 'mm',
        format: 'a4',
        orientation: 'portrait'
      },
      pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
    };

    html2pdf()
      .set(options)
      .from(element)
      .toPdf()
      .get('pdf')
      .then(pdf => {
        const totalPages = pdf.internal.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          pdf.setPage(i);
          pdf.setFontSize(10);
          pdf.text(`Page ${i} of ${totalPages}`, 180, 287);
          pdf.setDrawColor(0);
          pdf.rect(5, 5, 200, 287);
        }
      })
      .save();
  };

  return (
    <div className="p-4">
    <div className="mb-6 mt-2 p-4 border border-gray-300 rounded bg-white shadow">
  <Stepper currentStep={7} />
</div>

{/* Step 7 is REVIEW */}
      <div ref={pdfRef} className="bg-white text-black p-4">
        <div className="text-center mb-4">
          <h2 className="text-xl font-bold">MEASUREMENT SHEET</h2>
          <p className="text-sm font-medium uppercase">Name of Work: {nameOfWork}</p>
        </div>

        <table className="w-full border text-sm text-center border-collapse">
          <thead className="bg-gray-100">
            <tr>
              <th className="border">Sr.No</th>
              <th className="border">Item No</th>
              <th className="border" colSpan="2">Description of Item</th>
              <th className="border">No.</th>
              <th className="border">L</th>
              <th className="border">B/W</th>
              <th className="border">D/H</th>
              <th className="border">Quantity</th>
              <th className="border">Floor Lift/Rise</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item, index) => (
              <React.Fragment key={item.id}>
                <tr>
                  <td className="border">{index + 1}</td>
                  <td className="border">{item.itemNo}</td>
                  <td className="border" colSpan="7">{item.descriptionOfItem}</td>
                  <td className="border">{item.floorLiftRise}</td>
                </tr>

                {item.measurements && item.measurements.map((m, mi) => (
                  <tr key={mi} className="text-xs">
                    <td className="border"></td>
                    <td className="border"></td>
                    <td className="border" colSpan="2">{m.description}</td>
                    <td className="border">{m.number} x {m.multiplyNumber}</td>
                    <td className="border">{m.length}</td>
                    <td className="border">{m.width}</td>
                    <td className="border">{m.height}</td>
                    <td className="border font-bold">{m.quantity}</td>
                    <td className="border">{m.unit}</td>
                  </tr>
                ))}

                {item.measurements?.length > 0 && (
                  <tr className="font-bold bg-gray-50">
                    <td colSpan="8" className="text-right border pr-2">Net Quantity:</td>
                    <td className="border">{
                      item.measurements.reduce((sum, m) => sum + parseFloat(m.quantity || 0), 0).toFixed(2)
                    }</td>
                    <td className="border">{item.measurements[0]?.unit}</td>
                  </tr>
                )}
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </div>

      <div className="mt-4 text-center">
        <button
          onClick={exportToPDF}
          className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700"
        >
          Generate PDF
        </button>
      </div>
    </div>
  );
};

export default PDFGenerator;
