// WorkOrderDetails.jsx component

import React, { useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { motion } from 'framer-motion';

const WorkOrderDetails = ({ API_BASE_URL, jwtToken, fetchSubworks }) => {
  const [workOrderInfo, setWorkOrderInfo] = useState({
    workOrderId: '',
    nameOfWork: '',
    ssr: '',
    area: '',
    status: '',
    revisionStage: '',
    reviseId: '',
    reviseno: '',
    autogenerated: ''
  });
  const [isLoading, setIsLoading] = useState(false);

  // Animation variants
  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } }
  };

  // Load work order information on component mount
  useEffect(() => {
    // Check if we're in edit mode
    const isEditMode = localStorage.getItem("editMode") === "true";
    const workOrderId = localStorage.getItem('workorderId');
    
    // Initialize workOrderInfo based on whether we're in edit mode or not
    if (isEditMode) {
      // In edit mode, use the edit_ prefixed localStorage values
      const workOrderInfo = {
        workOrderId: workOrderId || '',
        nameOfWork: localStorage.getItem('edit_nameOfWork') || '',
        ssr: localStorage.getItem('edit_ssr') || '',
        area: localStorage.getItem('edit_area') || 'General Area',
        status: localStorage.getItem('status') || '',
        revisionStage: localStorage.getItem('revisionStage') || '',
        reviseId: localStorage.getItem('reviseId') || '',
        reviseno: localStorage.getItem('reviseno') || '',
        autogenerated: localStorage.getItem('autogenerated') || ''
      };
      setWorkOrderInfo(workOrderInfo);
    } else {
      // Not in edit mode, use regular localStorage values
      const workOrderInfo = {
        workOrderId: workOrderId || '',
        nameOfWork: localStorage.getItem('nameOfWork') || '',
        ssr: localStorage.getItem('ssr') || '',
        area: localStorage.getItem('area') || '',
        status: localStorage.getItem('status') || '',
        revisionStage: localStorage.getItem('revisionStage') || '',
        reviseId: localStorage.getItem('reviseId') || '',
        reviseno: localStorage.getItem('reviseno') || '',
        autogenerated: localStorage.getItem('autogenerated') || ''
      };
      setWorkOrderInfo(workOrderInfo);
    }
    
    // Then fetch complete and up-to-date information from API
    const fetchWorkOrderDetails = async () => {
      if (!workOrderId) {
        toast.error('No work order ID found');
        return;
      }
      
      setIsLoading(true);
      try {
        const response = await fetch(`${API_BASE_URL}/workorders/${workOrderId}`, {
          headers: {
            "Authorization": `Bearer ${jwtToken}`,
            "Accept": "*/*"
          }
        });
        
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
        
        const data = await response.json();
        
        // Update state with fresh data from API, but respect edit mode values if present
        setWorkOrderInfo(prevInfo => {
          // If in edit mode, preserve edit mode values, otherwise use API data
          return {
            ...prevInfo,
            nameOfWork: isEditMode ? prevInfo.nameOfWork : (data.nameOfWork || prevInfo.nameOfWork),
            ssr: isEditMode ? prevInfo.ssr : (data.ssr || prevInfo.ssr),
            area: isEditMode ? prevInfo.area : (data.area || prevInfo.area),
            status: data.status || prevInfo.status,
            autogenerated: data.workOrderID || prevInfo.autogenerated
          };
        });
        
        // Only update localStorage with fresh data if NOT in edit mode
        if (!isEditMode) {
          localStorage.setItem('nameOfWork', data.nameOfWork);
          localStorage.setItem('ssr', data.ssr);
          localStorage.setItem('area', data.area);
          localStorage.setItem('status', data.status);
          localStorage.setItem('autogenerated', data.workOrderID);
        }
        
        toast.success('Work order details refreshed successfully');
      } catch (error) {
        console.error("Error fetching work order details:", error);
        toast.error(`Failed to fetch work order details: ${error.message}`);
      } finally {
        setIsLoading(false);
      }
    };
    
    // Also fetch current revision details
    const fetchCurrentRevision = async () => {
      const reviseId = localStorage.getItem('reviseId');
      if (!reviseId) {
        console.log("No revision ID found");
        return;
      }
      
      try {
        const response = await fetch(`${API_BASE_URL}/workorder-revisions/${reviseId}`, {
          headers: {
            "Authorization": `Bearer ${jwtToken}`,
            "Accept": "*/*"
          }
        });
        
        if (!response.ok) {
          throw new Error(`HTTP error! Status: ${response.status}`);
        }
        
        const data = await response.json();
        
        // Update state with fresh revision data
        setWorkOrderInfo(prevInfo => ({
          ...prevInfo,
          reviseno: data.reviseNumber || prevInfo.reviseno,
          revisionStage: data.revisionStage || prevInfo.revisionStage
        }));
        
        // Update localStorage with fresh revision data
        localStorage.setItem('reviseno', data.reviseNumber);
        localStorage.setItem('revisionStage', data.revisionStage);
      } catch (error) {
        console.error("Error fetching revision details:", error);
      }
    };
    
    // Function to fetch item options
    const fetchItemOptions = async () => {
      // Implementation for fetching item options
      // This was mentioned in your code but not fully provided
    };
    
    // Function to fetch revisions
    const fetchRevisions = async (workOrderId) => {
      if (!workOrderId) return;
      
      try {
        const response = await fetch(
          `${API_BASE_URL}/workorder-revisions/ByWorkorderId/${workOrderId}`,
          {
            headers: {
              Authorization: `Bearer ${jwtToken}`,
              Accept: '*/*',
            },
          }
        );

        if (!response.ok) throw new Error(`Error: ${response.status}`);

        const allRevisions = await response.json();

        const uniqueSorted = [...new Set(
          allRevisions
            .filter((rev) => rev.deletedFlag.toLowerCase() !== 'yes')
            .map((rev) => rev.reviseNumber)
        )].sort((a, b) => parseFloat(a) - parseFloat(b));

        console.log("Valid revisions:", uniqueSorted);
        toast.success(`Revision List: ${uniqueSorted.join(', ')}`);

      } catch (err) {
        console.error('Failed to fetch revisions:', err);
        toast.error('Error loading revision history.');
      }
    };
    
    // Run the API calls if we have a work order ID
    if (workOrderId) {
      fetchWorkOrderDetails();
      fetchCurrentRevision();
      fetchRevisions(workOrderId);
      if (typeof fetchSubworks === 'function') {
        const reviseId = localStorage.getItem('reviseId');
        fetchSubworks(reviseId, workOrderId);
      }
    }
    
    // Also fetch item options for later use
    // fetchItemOptions();
  }, [API_BASE_URL, jwtToken, fetchSubworks]);

  return (
    <motion.div 
      className="bg-white border border-gray-200 rounded-lg p-6 mb-6 shadow-md" 
      variants={itemVariants}
      initial="hidden"
      animate="visible"
    >
      <h2 className="text-xl font-bold mb-4 text-blue-700 border-b pb-2">Work Order Details</h2>
      {isLoading ? (
        <div className="flex justify-center items-center h-24">
          <p>Loading work order details...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="flex flex-col">
            <span className="text-gray-600 text-sm">Estimate ID</span>
            <span className="font-semibold text-lg">{workOrderInfo.autogenerated || 'N/A'}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-gray-600 text-sm">Revision No</span>
            <span className="font-semibold text-lg">{workOrderInfo.reviseno || 'N/A'}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-gray-600 text-sm">Specified Area</span>
            <span className="font-semibold text-lg">{workOrderInfo.area || 'N/A'}</span>
          </div>
          <div className="col-span-2 flex flex-col">
            <span className="text-gray-600 text-sm">Name Of Work</span>
            <span className="font-semibold text-lg">{workOrderInfo.nameOfWork || 'N/A'}</span>
          </div>
          <div className="flex flex-col">
            <span className="text-gray-600 text-sm">SSR</span>
            <span className="font-semibold text-lg">{workOrderInfo.ssr || 'N/A'}</span>
          </div>
        </div>
      )}
    </motion.div>
  );
};

export default WorkOrderDetails;